/**
 * Arabic strings - Single source of truth for console app.
 * All user-facing text MUST come from here.
 */

export const ar = {
  common: {
    clientFallback: "العميل",
  },

  meta: {
    title: "بوابة العملاء - مودونتي",
    description: "بوابة مودونتي للعملاء. سجّل الدخول للوصول إلى لوحة التحكم.",
  },

  login: {
    clientPortal: "بوابة العملاء",
    signInCopy: "سجّل الدخول للوصول إلى لوحة التحكم والمحتوى والإحصائيات.",
    yourDashboard: "لوحتك",
    trackEverything: "تابع كل شيء",
    secureLogin: "تسجيل آمن",
    safeAccountAccess: "دخول آمن لحسابك",
    accountSecurity: "أمان الحساب",
    protectedData: "بياناتك محمية",
    realtimeUpdates: "تحديثات فورية",
    stayInformed: "ابقَ على اطلاع",
    secureAccess: "وصول آمن للعملاء.",
    referTitle: "أدخل زميلاً واحصل على 5 مقالات مجانية",
    referDesc: "عند اشتراك من أدخلته، ستحصل على 5 مقالات مجانية.",
    signIn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول…",
    useEmailOrSlug: "استخدم بريدك أو معرف العميل وكلمة المرور للدخول.",
    emailOrSlug: "البريد أو معرف العميل",
    placeholderIdentifier: "example@mail.com أو معرف-العميل",
    password: "كلمة المرور",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
    somethingWrong: "حدث خطأ. جرّب مرة أخرى.",
  },

  logo: {
    alt: "بوابة العملاء - مودونتي",
  },

  nav: {
    dashboard: "لوحة التحكم",
    seo: "معلومات مهمة",
    articles: "المقالات",
    content: "المحتوى",
    media: "الوسائط",
    analytics: "الإحصائيات",
    campaigns: "الحملات",
    comments: "التعليقات",
    questions: "أسئلة الزوار",
    faqs: "الأسئلة الشائعة",
    subscribers: "المشتركون",
    leads: "العملاء المحتملون",
    profile: "معلومات الشركة",
    settings: "الإعدادات",
    support: "الدعم",
    signOut: "تسجيل الخروج",
    expandSidebar: "توسيع القائمة",
    collapseSidebar: "طي القائمة",
  },

  header: {
    openMenu: "فتح القائمة",
  },

  dashboard: {
    welcome: "مرحباً بعودتك. إليك ملخص الأداء.",
    subscription: "الاشتراك",
    currentPlan: "الباقة الحالية",
    subStatusActive: "نشط",
    subStatusInactive: "غير نشط",
    subStatusExpired: "منتهي",
    subStatusCancelled: "ملغي",
    paymentPaid: "مدفوع",
    paymentUnpaid: "غير مدفوع",
    paymentPending: "قيد الانتظار",
    perYear: "سنوياً",
    currencySar: "ريال سعودي",
    content: "المحتوى",
    articlesThisMonth: "المقالات هذا الشهر",
    subscribers: "المشتركون",
    newsletterList: "قائمة النشرة",
    totalSubscribers: "إجمالي المشتركين",
    articles: "المقالات",
    manageApprove: "المقالات والموافقات",
    pendingApproval: "بانتظار الموافقة",
    allApproved: "تمت الموافقة على الكل",
    viewContent: "عرض المحتوى",
    analytics: "الإحصائيات",
    viewsEngagement: "المشاهدات والتفاعل",
    viewAnalytics: "عرض الإحصائيات",
    comments: "التعليقات",
    moderationQueue: "انتظار المراجعة",
    pendingReview: "بانتظار المراجعة",
    allReviewed: "تمت مراجعة الكل",
    moderateComments: "مراجعة التعليقات",
    media: "الوسائط",
    assetsBranding: "الملفات والهوية",
    manageLibrary: "إدارة المكتبة",
    viewMedia: "عرض الوسائط",
    support: "الدعم",
    contactMessages: "رسائل التواصل",
    viewMessages: "عرض الرسائل",
    manageSupport: "إدارة الدعم",
    engagementScore: "درجة التفاعل",
    activeUsers: "المستخدمون النشطون",
    avgTime: "متوسط الوقت",
    scroll: "التمرير",
    returnRate: "معدل الزوار العائدين",
    days7: "آخر 7 أيام",
    days30: "آخر 30 يوم",
    interactions: "التفاعلات",
    conversions: "التحويلات",
    likes: "إعجابات",
    shares: "مشاركات",
    commentsLabel: "تعليقات",
    rate: "النسبة",
    bounce: "نسبة الارتداد",
    topPerforming: "أفضل المقالات أداءً",
    byViewsEngagement: "حسب المشاهدات والتفاعل والتحويلات",
    byViews: "حسب المشاهدات",
    byEngagement: "حسب التفاعل",
    views: "مشاهدة",
    score: "الدرجة",
    trafficSources: "مصادر الزيارات",
    last30Days: "آخر 30 يوم",
    recentActivity: "النشاط الأخير",
    latestUpdates: "آخر التحديثات والأحداث",
    noArticles: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
    noTraffic: "لا توجد بيانات زيارات بعد. ستتراكم خلال أيام من نشر المقالات.",
    noActivity: "لا يوجد نشاط حديث.",
    newArticlePublished: "مقالة جديدة نُشرت",
    newComment: "تعليق جديد",
    newSubscriber: "مشترك جديد",
    onArticle: "على المقالة",
    unknown: "غير معروف",
  },

  articles: {
    manageApproveArticles: "إدارة المقالات والموافقة عليها",
    pendingApprovalTab: "بانتظار الموافقة",
    published: "منشور",
    allArticles: "كل المقالات",
    noPending: "لا توجد مقالات بانتظار الموافقة. سنخبرك عند وصول مقالة جديدة.",
    noPublished: "لا توجد مقالات منشورة بعد.",
    noArticlesYet: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
    created: "تاريخ الإنشاء",
    pendingApprovalStatus: "بانتظار الموافقة",
    statusPublished: "منشور",
    statusDraft: "مسودة",
    statusScheduled: "مجدول",
    statusWriting: "قيد الكتابة",
    statusArchived: "مؤرشف",
    words: "كلمة",
    minRead: "دقيقة قراءة",
    tag: "وسم",
    tags: "وسوم",
    preview: "معاينة",
    approve: "موافقة",
    requestChanges: "طلب تعديلات",
    approving: "جاري الموافقة…",
    approveArticle: "الموافقة على المقالة",
    backToArticles: "العودة للمقالات",
    approveConfirm: "تأكيد الموافقة على المقالة؟",
    approveFailed: "ما تمت الموافقة على المقالة. جرّب مرة أخرى.",
    requestFailed: "ما تم إرسال طلب التعديل. جرّب مرة أخرى.",
    errorOccurred: "حدث خطأ",
    basicContent: "المحتوى الأساسي",
    titleSlugExcerpt: "العنوان والرابط والملخص والبيانات",
    title: "العنوان",
    slug: "الرابط",
    excerpt: "الملخص",
    status: "الحالة",
    datePublished: "تاريخ النشر",
    inLanguage: "اللغة",
    articleContent: "محتوى المقالة",
    fullArticleBody: "نص المقالة كاملاً",
    format: "التنسيق",
    formatLabel: "التنسيق",
    wordsCount: "كلمة",
    wordCount: "عدد الكلمات",
    readingTime: "وقت القراءة",
    contentDepth: "عمق المحتوى",
    characters: "حرف",
    credentials: "المؤهلات",
    relationships: "العلاقات",
    clientCategoryAuthor: "العميل والتصنيف والكاتب والوسوم",
    client: "العميل",
    category: "التصنيف",
    author: "الكاتب",
    featuredImage: "الصورة الرئيسية",
    mainArticleImage: "صورة المقالة الرئيسية",
    noImage: "لا توجد صورة",
    altText: "النص البديل",
    caption: "التسمية التوضيحية",
    imageGallery: "معرض الصور",
    imagesCount: "صورة",
    galleryImage: "صورة المعرض",
    min: "دقيقة",
    seoMeta: "بيانات البحث",
    searchEngineOpt: "تحسين محركات البحث",
    seoTitle: "عنوان البحث",
    seoTitleLabel: "عنوان البحث",
    seoDescription: "وصف البحث",
    seoDescriptionLabel: "وصف البحث",
    metaRobots: "إعدادات الروبوتات",
    canonicalUrl: "الرابط الأساسي",
    openGraph: "مشاركة الشبكات",
    ogType: "نوع المشاركة",
    ogArticleAuthor: "كاتب المقالة",
    ogImage: "صورة المشاركة",
    ogPublishedTime: "وقت النشر للمشاركة",
    twitterCards: "بطاقات تويتر",
    twitterCard: "بطاقة تويتر",
    twitterCardType: "نوع بطاقة تويتر",
    twitterSite: "حساب تويتر",
    twitterCreator: "المنشئ",
    faqs: "الأسئلة الشائعة",
    questionsCount: "سؤال",
    relatedArticles: "مقالات ذات صلة",
    technicalSeo: "بيانات تقنية للبحث",
    sitemapSettings: "خريطة الموقع والإعدادات التقنية",
    sitemapPriority: "أهمية الصفحة في البحث",
    sitemapChangeFreq: "تكرار التحديث",
    breadcrumbPath: "مسار التصفح",
    jsonld: "بيانات البحث المنظمة",
    schemaOrg: "بيانات منظمة لجوجل",
    lastGenerated: "آخر تحديث",
    citations: "المراجع",
    sourcesCount: "مصدر",
    requestChangesTitle: "طلب تعديلات",
    feedbackLabel: "ملاحظاتك أو التعديلات المطلوبة",
    feedbackPlaceholder: "صف التعديلات التي تود رؤيتها...",
    feedbackSent: "سنرسل ملاحظاتك لفريق المحتوى.",
    cancel: "إلغاء",
    sendFeedback: "إرسال الملاحظات",
    sending: "جاري الإرسال…",
    pleaseProvideFeedback: "أضف ملاحظاتك",
    articleLabel: "المقالة:",
    publishedOn: "نُشر في",
    articlePreviewTitle: "معاينة المقالة",
    reviewBeforeApproval: "تفقد المقالة قبل الموافقة",
    socialSharing: "مشاركة على الشبكات الاجتماعية",
    twitterSharingDesc: "بيانات مشاركة تويتر",
    articlesCount: "مقالة",
  },

  content: {
    articlesProgress: "تقدم المقالات الشهري",
    monthlyQuota: "الحصة الشهرية",
    publishedThisMonth: "المقالات المنشورة هذا الشهر",
    recentArticles: "آخر المقالات",
    yourContentLibrary: "مكتبة المحتوى",
    thisMonth: "هذا الشهر",
  },

  media: {
    mediaLibrary: "مكتبة الوسائط",
    viewMediaAssets: "عرض ملفات الوسائط",
    totalMedia: "إجمالي الوسائط",
    totalMediaLabel: "إجمالي الوسائط:",
    totalSize: "الحجم الإجمالي",
    files: "ملف",
    filesCount: "ملف",
    brandingAssets: "أصول الهوية",
    mediaGallery: "معرض الوسائط",
    viewLogoSocial: "شاهد الشعار وصور التواصل",
    logo: "الشعار",
    openGraphImage: "صورة المشاركة",
    twitterCardImage: "صورة بطاقة تويتر",
    all: "الكل",
    logos: "الشعارات",
    posts: "المنشورات",
    ogImages: "صور المشاركة",
    usedInPlaces: "مستخدم في {n} مكان",
    notUsed: "غير مستخدم",
    noMedia: "لا توجد ملفات بعد. ستظهر هنا الصور المستخدمة في مقالاتك.",
  },

  analytics: {
    title: "الإحصائيات",
    comprehensiveAnalytics: "إحصائيات وأداء",
    views7d: "مشاهدات (7 أيام)",
    views30d: "مشاهدات (30 يوماً)",
    totalPageViews: "إجمالي المشاهدات",
    articles: "المقالات",
    client: "العميل",
    engagementRate: "نسبة التفاعل",
    conversionRate: "نسبة التحويل",
    trafficSources: "مصادر الزيارات",
    last30d: "آخر 30 يوم",
    noTraffic: "لا توجد بيانات زيارات بعد.",
    coreWebVitals: "تجربة الزائر على الموقع",
    performanceMetrics: "متوسط 30 يوم",
    engagementMetrics: "التفاعل",
    userBehavior: "سلوك المستخدم",
    timeOnPage: "وقت الصفحة",
    scrollDepth: "عمق التمرير",
    completionRate: "نسبة الإكمال",
    readingTime: "وقت القراءة",
    conversions: "التحويلات",
    totalConversions: "إجمالي التحويلات",
    conversionTypes: "أنواع التحويلات",
    noConversions: "لا تحويلات بعد",
    campaignPerformance: "أداء الحملات",
    activeCampaigns: "الحملات النشطة",
    impressions: "مرات الظهور",
    clicks: "نقرات",
    topPerformingArticles: "أفضل المقالات",
    articlesRankedByViews: "حسب المشاهدات (30 يوماً)",
    views: "مشاهدة",
    scroll: "تمرير",
    noArticles: "لا توجد مقالات بعد.",
    topClickedLinks: "أكثر الروابط نقرة",
    mostClickedLinks: "في المقالات (30 يوماً)",
    users: "مستخدم",
    noLinkClickData: "لا توجد بيانات نقرات بعد.",
    clientPageViews: "مشاهدات صفحة العميل",
    brandPageAnalytics: "صفحة العلامة والملف (30 يوماً)",
    totalClientViews: "إجمالي المشاهدات",
    uniqueVisitors: "زوار فريدون",
    topReferrers: "أهم المصادر",
    noReferrerData: "لا توجد بيانات مصادر بعد.",
    engaged: "تفاعل",
    bounced: "ارتداد",
    lcp: "سرعة ظهور المحتوى",
    cls: "ثبات الصفحة",
    inp: "سرعة الاستجابة",
    ttfb: "سرعة الخادم",
    tbt: "وقت الانشغال",
    sAvg: "ث متوسط",
    percentAvg: "% متوسط",
    scrollDepthDist: "توزيع عمق التمرير",
    topCtaClicks: "أكثر الأزرار نقرة",
    ctaClicksDesc: "الأزرار والروابط المتتبعة (30 يوماً)",
    noCtaData: "لا توجد بيانات نقرات بعد.",
    ctaTypeButton: "زر",
    ctaTypeLink: "رابط",
    ctaTypeForm: "نموذج",
    ctaTypeBanner: "لافتة",
    ctaTypePopup: "نافذة منبثقة",
    sourceOrganic: "بحث جوجل",
    sourceDirect: "زيارة مباشرة",
    sourceReferral: "إحالة من موقع آخر",
    sourceSocial: "شبكات اجتماعية",
    sourcePaid: "إعلان مدفوع",
    sourceUnknown: "غير معروف",
  },

  leads: {
    title: "تقييم العملاء المحتملين",
    trackQualify: "تتبع الزوار الأكثر تفاعلاً",
    hotLeads: "عملاء ساخنون",
    warmLeads: "عملاء دافئون",
    coldLeads: "عملاء باردون",
    qualified: "مؤهلون",
    avgScore: "متوسط الدرجة",
    highEngagement: "تفاعل عالي",
    moderateEngagement: "تفاعل متوسط",
    lowEngagement: "تفاعل منخفض",
    readyForOutreach: "جاهزون للتواصل",
    outOf100: "من 100",
    leadsOverview: "ملخص العملاء المحتملين",
    leadsCount: "عميل محتمل",
    all: "الكل",
    hot: "ساخن",
    warm: "دافئ",
    cold: "بارد",
    contact: "جهة الاتصال",
    level: "المستوى",
    score: "الدرجة",
    pages: "الصفحات",
    timeMin: "الوقت (دقيقة)",
    interactions: "التفاعلات",
    conversions: "التحويلات",
    lastActive: "آخر نشاط",
    noLeadsFound: "لا يوجد عملاء محتملون بعد.",
    noLeadsHint: "اضغط \"تحديث الدرجات\" لحساب نقاط الزوار بناءً على تفاعلهم مع المحتوى.",
    noContact: "لا يوجد اتصال",
    anonymous: "مجهول",
    unqualified: "غير مؤهل",
    refreshScores: "تحديث الدرجات",
    refreshing: "جاري التحديث…",
    refreshScoresSuccess: "تم تحديث الدرجات",
    refreshScoresError: "ما تم تحديث الدرجات. جرّب مرة أخرى.",
    never: "أبداً",
  },

  subscribers: {
    title: "إدارة المشتركين",
    manageNewsletter: "إدارة مشتركي النشرة والامتثال للخصوصية",
    all: "الكل",
    active: "نشط",
    subscribedUsers: "مشتركون في النشرة",
    unsubscribed: "غير مشترك",
    leftTheList: "غادر القائمة",
    gdprConsent: "موافقة الخصوصية",
    withConsent: "مع الموافقة",
    thisMonth: "هذا الشهر",
    newSubscribers: "مشتركون جدد",
    total: "الإجمالي",
    allSubscribers: "كل المشتركين",
    subscribersList: "قائمة المشتركين",
    subscribersCount: "مشترك",
    exportCsv: "تصدير CSV",
    email: "البريد الإلكتروني",
    subscribedAt: "تاريخ الاشتراك",
    status: "الحالة",
    noSubscribers: "لا يوجد مشتركون بعد. سيظهرون هنا عند الاشتراك في النشرة.",
    name: "الاسم",
    consent: "الموافقة",
    actions: "الإجراءات",
    noConsent: "بدون موافقة",
    unsubscribeFailed: "ما تم إلغاء الاشتراك. جرّب مرة أخرى.",
    resubscribeFailed: "ما تمت إعادة الاشتراك. جرّب مرة أخرى.",
    deleteSubscriberConfirm: "تأكيد حذف هذا المشترك؟",
    deleteFailed: "ما تم الحذف. جرّب مرة أخرى.",
    exportFailed: "ما تم التصدير. جرّب مرة أخرى.",
  },

  campaigns: {
    beta: "نسخة تجريبية",
    title: "تحليلات الحملات",
    trackCampaigns: "تتبع حملاتك وأداء روابطك التسويقية",
    totalCampaigns: "إجمالي الحملات",
    activeLast30Days: "نشطة في آخر 30 يوم",
    totalClicks: "إجمالي النقرات",
    conversions: "التحويلات",
    totalCost: "التكلفة الإجمالية",
    campaignSpend: "إنفاق الحملات",
    campaignPerformance: "أداء الحملات",
    detailedMetrics: "مقاييس تفصيلية لكل حملة",
    noCampaignData: "لا توجد بيانات حملات بعد.",
    noCampaignHint: "لبدء التتبع، أضف وسوم لروابط حملاتك — مثال: /articles/slug?utm_source=instagram&utm_campaign=ramadan",
    utmAnalysis: "تحليل روابط الحملات",
    trackBySource: "حسب المصدر والوسيط والحملة",
    noUtmData: "لا توجد بيانات تتبع روابط بعد.",
    source: "المصدر",
    medium: "الوسيط",
    campaign: "الحملة",
    type: "النوع",
    impressions: "مرات الظهور",
    clicks: "النقرات",
    ctr: "نسبة النقر إلى الظهور",
    cvr: "نسبة التحويل",
    cost: "التكلفة",
    roi: "العائد على الإنفاق",
    convRate: "نسبة التحويل",
    rate: "النسبة",
    visits: "الزيارات",
    conversionRate: "نسبة التحويل",
  },

  comments: {
    title: "مراجعة التعليقات",
    reviewModerate: "مراجعة التعليقات",
    pending: "بانتظار المراجعة",
    awaitingReview: "بانتظار المراجعة",
    approved: "معتمد",
    publishedComments: "التعليقات المنشورة",
    rejected: "مرفوض",
    rejectedComments: "التعليقات المرفوضة",
    total: "الإجمالي",
    all: "الكل",
    allComments: "كل التعليقات",
    commentsCount: "تعليق",
    approveSelected: "الموافقة على المحدد",
    rejectSelected: "رفض المحدد",
    noCommentsFound: "لا توجد تعليقات بعد. ستظهر هنا عندما يرد القرّاء على مقالاتك.",
    anonymous: "مجهول",
    noEmail: "لا يوجد بريد",
    approveComment: "الموافقة",
    rejectComment: "الرفض",
    deleteComment: "الحذف",
    deleteConfirm: "تأكيد حذف هذا التعليق؟",
    approveFailed: "ما تمت الموافقة على التعليق. جرّب مرة أخرى.",
    rejectFailed: "ما تم رفض التعليق. جرّب مرة أخرى.",
    deleteFailed: "ما تم حذف التعليق. جرّب مرة أخرى.",
    bulkApproveFailed: "ما تمت الموافقة الجماعية. جرّب مرة أخرى.",
    bulkRejectFailed: "ما تم الرفض الجماعي. جرّب مرة أخرى.",
    replies: "رد",
    replyTo: "رد على:",
  },

  faqs: {
    title: "الأسئلة الشائعة",
    description: "راجع الأسئلة المقترحة من فريق مودونتي ووافق عليها أو ارفضها.",
    pending: "بانتظار الموافقة",
    published: "منشورة",
    rejected: "مرفوضة",
    total: "الإجمالي",
    all: "الكل",
    faqsCount: "سؤال",
    awaitingApproval: "بانتظار موافقتك",
    publishedFaqs: "أسئلة منشورة",
    allFaqs: "كل الأسئلة",
    fromArticle: "من مقال",
    approve: "نشر",
    reject: "رفض",
    approving: "جاري النشر…",
    rejecting: "جاري الرفض…",
    editAnswer: "تعديل الإجابة",
    answerLabel: "الإجابة",
    answerPlaceholder: "اكتب إجابتك هنا…",
    save: "حفظ التعديل",
    saving: "جاري الحفظ…",
    noFaqs: "لا توجد أسئلة بعد.",
    approveFailed: "ما تم النشر. جرّب مرة أخرى.",
    rejectFailed: "ما تم الرفض. جرّب مرة أخرى.",
    saveFailed: "ما تم الحفظ. جرّب مرة أخرى.",
    source: "المصدر",
    sourceChatbot: "من الشات بوت",
    sourceManual: "يدوي",
  },

  questions: {
    title: "أسئلة الزوار",
    description: "عرض أسئلة الزوار على المقالات والرد عليها.",
    pending: "بانتظار الرد",
    answered: "تم الرد",
    total: "الإجمالي",
    all: "الكل",
    questionsCount: "سؤال",
    awaitingReply: "بانتظار الرد",
    publishedReplies: "ردود منشورة",
    allQuestions: "كل الأسئلة",
    reply: "رد",
    replyPlaceholder: "اكتب ردك هنا…",
    fromArticle: "من مقال",
    submitter: "المرسل",
    anonymous: "مجهول",
    noEmail: "لا يوجد بريد",
    yourReply: "ردك:",
    noQuestions: "لا توجد أسئلة بعد. ستظهر هنا عندما يسأل الزوار على مقالاتك.",
    replySuccess: "تم إرسال الرد",
    replyFailed: "ما تم إرسال الرد. جرّب مرة أخرى.",
  },

  support: {
    title: "رسائل الدعم",
    manageContact: "إدارة وردود نماذج التواصل",
    all: "الكل",
    new: "جديد",
    archived: "مُؤرشف",
    unreadMessages: "رسائل غير مقروءة",
    read: "مقروء",
    messagesRead: "رسائل مقروءة",
    replied: "تم الرد",
    messagesReplied: "رسائل تم الرد عليها",
    total: "الإجمالي",
    allMessages: "كل الرسائل",
    messages: "الرسائل",
    messageDetails: "تفاصيل الرسالة",
    selectToView: "اختر رسالة لعرض تفاصيلها",
    noMessagesFound: "لا توجد رسائل بعد.",
    from: "من",
    subject: "الموضوع",
    received: "تاريخ الاستلام",
    message: "الرسالة",
    referrer: "المصدر",
    markRead: "مقروء",
    markReplied: "تم الرد",
    markArchived: "مُؤرشف",
    delete: "حذف",
    deleteConfirm: "تأكيد حذف هذه الرسالة؟",
    updateFailed: "ما تم تحديث الرسالة. جرّب مرة أخرى.",
    deleteFailed: "ما تم حذف الرسالة. جرّب مرة أخرى.",
    reply: "رد",
    yourReply: "ردك",
    sendReply: "إرسال الرد",
    replyViaEmail: "إرسال الرد عبر البريد",
    replySuccess: "تم إرسال الرد بنجاح",
    replyFailed: "ما تم إرسال الرد. جرّب مرة أخرى.",
    replySavedEmailFailed: "تم حفظ الرد لكن ما تم إرسال البريد.",
  },

  profile: {
    title: "معلومات الشركة",
    description: "تعديل بيانات الشركة والتواصل",
    basicInfo: "البيانات الأساسية",
    name: "اسم الشركة",
    legalName: "الاسم القانوني",
    alternateName: "الاسم البديل",
    url: "الموقع الإلكتروني",
    slogan: "الشعار",
    organizationDescription: "وصف الشركة",
    contactInfo: "معلومات التواصل",
    contactType: "نوع جهة الاتصال",
    address: "العنوان",
    addressStreet: "الشارع",
    addressCity: "المدينة",
    addressCountry: "الدولة",
    addressPostalCode: "الرمز البريدي",
    addressRegion: "المنطقة",
    addressNeighborhood: "الحي",
    addressBuildingNumber: "رقم المبنى",
    addressAdditionalNumber: "الرقم الإضافي",
    saudiGulf: "السجل التجاري والضرائب",
    commercialRegistrationNumber: "رقم السجل التجاري",
    vatID: "الرقم الضريبي (زاتكا)",
    taxID: "الرقم الضريبي",
    legalForm: "الشكل القانوني",
    business: "معلومات الأعمال",
    industry: "القطاع",
    targetAudience: "الجمهور المستهدف",
    organizationType: "نوع المنظمة",
    foundingDate: "تاريخ التأسيس",
    businessBrief: "نبذة عن الأعمال",
    socialProfiles: "الحسابات الاجتماعية",
    socialProfilesHint: "رابط واحد في كل سطر (لينكدإن، تويتر، فيسبوك)",
    seo: "بيانات البحث",
    seoTitle: "عنوان البحث",
    seoDescription: "وصف البحث",
    canonicalUrl: "الرابط الأساسي",
    canonicalUrlHint: "إذا نُسخت مقالتك في مكان آخر، هذا الرابط يخبر جوجل بالمصدر الأصلي.",
    twitter: "تويتر",
    twitterTitle: "عنوان تويتر",
    twitterDescription: "وصف تويتر",
    twitterSite: "@اسم_المستخدم",
    seoSettings: "إعدادات البحث",
    technicalProfile: "الملف التقني",
    platform: "المنصة",
    stagingUrl: "رابط الموقع التجريبي",
    seoGoals: "أهداف الظهور في البحث",
    primaryGoal: "الهدف الرئيسي",
    kpis: "مؤشرات النجاح (مثل: عدد الزوار، المبيعات)",
    goalsDisclaimer: "نساعدك نحدد الأولويات ونرتب الخطة. النتائج تتحقق تدريجياً وتتأثر بالمنافسة وجودة الموقع والاستمرارية — نعمل معك لأفضل نتيجة ممكنة دون وعد بأرقام أو مواعيد ثابتة.",
    successMetrics: "معايير النجاح",
    timeline: "الجدول الزمني",
    seoMetrics: "مقاييس البحث",
    domainAuthority: "قوة الموقع في البحث",
    backlinkCount: "عدد الروابط الخلفية",
    linkBuildingPolicy: "سياسة بناء الروابط",
    brandGuidelines: "إرشادات البراند",
    contentTone: "نبرة المحتوى",
    complianceConstraints: "قيود الامتثال",
    complianceIndustry: "قطاع الامتثال",
    restrictedClaims: "ادعاءات مقيدة",
    googleBusinessProfileUrl: "رابط ملف نشاطك التجاري على جوجل",
    forbiddenKeywords: "كلمات ممنوعة",
    forbiddenClaims: "ادعاءات ممنوعة",
    competitiveMentionsAllowed: "السماح بذكر المنافسين",
  },

  seo: {
    title: "معلومات مهمة",
    heroDescription:
      "«مدونتي» هي منصة تمكّن أصحاب الأعمال من الحصول على مقالات جاهزة ومتجددة ترفع ظهورهم على محركات البحث. ببساطة، هي تساعدك على نشر محتوى مدروس باستمرار دون الحاجة لأن تكتب بنفسك، مما يوفر لك الوقت ويعزز ظهور علامتك.",
    intake: "معلومات مهمة",
    competitors: "المنافسون",
    keywords: "الكلمات المفتاحية",
    project: "المشروع",
    addCompetitor: "إضافة منافس",
    addKeyword: "إضافة كلمة",
    name: "الاسم",
    url: "الرابط",
    notes: "ملاحظات",
    keyword: "الكلمة",
    intent: "النية",
    priority: "الأولوية",
    reason: "السبب",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    saveIntake: "حفظ الاستمارة",
    transactional: "معاملاتي",
    informational: "معلوماتي",
    commercial: "تجاري",
    goals: "الأهداف",
    budget: "الميزانية",
    contactPerson: "مَن نتواصل معه؟",
    reportingPreference: "شكل التقارير",
    weekly: "أسبوعي",
    monthly: "شهري",
    noCompetitors: "لا يوجد منافسون بعد.",
    noKeywords: "لا توجد كلمات مفتاحية بعد.",
    deleteConfirm: "تأكيد الحذف؟",
    keywordsTabNote: "أضف الكلمات المستهدفة من تبويب «الكلمات المفتاحية» أعلى الصفحة.",
  },

  settings: {
    profileSettings: "الملف والإعدادات",
    contactGtm: "التواصل وأدوات التتبع (اختياري)",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gtmContainerId: "معرّف Google Tag Manager (اختياري)",
    gtmHint: "إذا كنت تستخدم Google Tag Manager لتتبع الزوار، أدخل المعرّف هنا.",
    placeholderEmail: "example@mail.com",
    placeholderPhone: "+966...",
    placeholderGtm: "GTM-XXXXXXX",
    save: "حفظ",
    saving: "جاري الحفظ…",
    updateFailed: "ما تم التحديث. جرّب مرة أخرى.",
    somethingWrong: "حدث خطأ.",
    notifications: "إعدادات الإشعارات",
    notificationsDesc: "اختر ما تريد إشعارك به",
    articlePublished: "نشر مقالة جديدة",
    articleApproved: "الموافقة على مقالة",
    digest: "الملخص",
    digestNone: "بدون",
    digestWeekly: "أسبوعي",
    digestMonthly: "شهري",
    commentsNew: "تعليقات جديدة",
    supportReplies: "ردود الدعم",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordChanged: "تم تغيير كلمة المرور",
    wrongPassword: "كلمة المرور الحالية غير صحيحة",
    passwordsMismatch: "كلمة المرور الجديدة وتأكيدها لا تتطابقان",
    passwordMinLength: "كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل",
  },

  articleStats: {
    views: "المشاهدات",
    likes: "الإعجابات",
    dislikes: "عدم الإعجاب",
    comments: "التعليقات",
    questions: "الأسئلة",
    statsTitle: "إحصائيات المقال",
  },

  errors: {
    approveFailed: "ما تمت الموافقة على المقالة. جرّب مرة أخرى.",
    requestFailed: "ما تم إرسال طلب التعديل. جرّب مرة أخرى.",
    errorOccurred: "حدث خطأ",
    somethingWrong: "حدث خطأ. جرّب مرة أخرى.",
  },
} as const;
