/**
 * Arabic strings - Single source of truth for console app.
 * All user-facing text MUST come from here.
 */

export const ar = {
  common: {
    clientFallback: "العميل",
  },

  meta: {
    title: "بوابة العملاء - مودونتي",
    description: "بوابة مودونتي للعملاء. سجّل الدخول للوصول إلى لوحة التحكم.",
  },

  login: {
    clientPortal: "بوابة العملاء",
    signInCopy: "سجّل الدخول للوصول إلى لوحة التحكم والمحتوى والإحصائيات.",
    yourDashboard: "لوحتك",
    trackEverything: "تابع كل شيء",
    secureLogin: "تسجيل آمن",
    safeAccountAccess: "دخول آمن لحسابك",
    accountSecurity: "أمان الحساب",
    protectedData: "بياناتك محمية",
    realtimeUpdates: "تحديثات فورية",
    stayInformed: "ابقَ على اطلاع",
    secureAccess: "وصول آمن للعملاء.",
    referTitle: "أدخل زميلاً واحصل على 5 مقالات مجانية",
    referDesc: "عند اشتراك من أدخلته، ستحصل على 5 مقالات مجانية.",
    signIn: "تسجيل الدخول",
    signingIn: "جاري تسجيل الدخول…",
    useEmailOrSlug: "استخدم بريدك أو معرف العميل وكلمة المرور للدخول.",
    emailOrSlug: "البريد أو معرف العميل",
    placeholderIdentifier: "example@mail.com أو معرف-العميل",
    password: "كلمة المرور",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
    somethingWrong: "حدث خطأ. جرّب مرة أخرى.",
  },

  logo: {
    alt: "بوابة العملاء - مودونتي",
  },

  nav: {
    dashboard: "لوحة التحكم",
    seo: "معلومات نشاطك",
    articles: "المقالات",
    content: "نشاط المحتوى",
    media: "الصور والملفات",
    analytics: "الإحصائيات",
    campaigns: "الحملات",
    comments: "التعليقات",
    questions: "أسئلة الزوار",
    faqs: "الأسئلة الشائعة",
    clientComments: "آراء حول الشركة",
    siteHealth: "صحة موقعك",
    subscribers: "مشتركو النشرة",
    leads: "العملاء المحتملون",
    profile: "بيانات شركتك",
    settings: "الإعدادات",
    support: "الدعم",
    signOut: "تسجيل الخروج",
    expandSidebar: "توسيع القائمة",
    collapseSidebar: "طي القائمة",
  },

  header: {
    openMenu: "فتح القائمة",
  },

  dashboard: {
    welcome: "هذي نظرتك السريعة على آخر 30 يوم — تابع وافتح أي قسم لمزيد من التفاصيل.",
    greetingFor: "مرحباً، {name}",

    // This-month summary
    thisMonth: "هذا الشهر",
    thisMonthArticles: "{n} مقال نُشر",
    thisMonthViews: "{n} مشاهدة",
    thisMonthSubscribers: "{n} مشترك جديد",

    // Section titles
    actionItemsTitle: "يحتاج انتباهك",
    actionItemsSubtitle: "أمور بانتظار قرارك أو متابعتك.",
    performanceTitle: "الأداء",
    performanceSubtitle: "مؤشّرات وصول محتواك ونشاط زوّارك.",
    audienceTitle: "الجمهور",
    audienceSubtitle: "نمو متابعيك وعمق تفاعلهم.",

    // Trends
    trendUp: "↗",
    trendDown: "↘",
    trendFlat: "→",
    vsLastWeek: "مقارنة بالأسبوع السابق",
    vsLastMonth: "مقارنة بالشهر السابق",
    noPrevData: "لا توجد بيانات سابقة للمقارنة بعد.",

    // Engagement benchmarks
    benchmarkExcellent: "ممتاز",
    benchmarkGood: "جيد",
    benchmarkAverage: "متوسط",
    benchmarkLow: "يحتاج تحسين",

    // Avg time formatting
    avgTimeMinutes: "{n} دقيقة",
    avgTimeManyMinutes: "أكثر من {n} دقيقة",

    subscription: "الاشتراك",
    currentPlan: "الباقة الحالية",
    subStatusActive: "نشط",
    subStatusInactive: "غير نشط",
    subStatusExpired: "منتهي",
    subStatusCancelled: "ملغي",
    paymentPaid: "مدفوع",
    paymentUnpaid: "غير مدفوع",
    paymentPending: "قيد الانتظار",
    perYear: "سنوياً",
    currencySar: "ريال سعودي",
    content: "المحتوى",
    articlesThisMonth: "المقالات هذا الشهر",
    subscribers: "المشتركون",
    newsletterList: "قائمة النشرة",
    totalSubscribers: "إجمالي المشتركين",
    articles: "المقالات",
    manageApprove: "المقالات والموافقات",
    pendingApproval: "بانتظار الموافقة",
    allApproved: "تمت الموافقة على الكل",
    viewContent: "عرض المحتوى",
    analytics: "الإحصائيات",
    viewsEngagement: "المشاهدات والتفاعل",
    viewAnalytics: "عرض الإحصائيات",
    comments: "التعليقات",
    moderationQueue: "انتظار المراجعة",
    pendingReview: "بانتظار المراجعة",
    allReviewed: "تمت مراجعة الكل",
    moderateComments: "مراجعة التعليقات",
    media: "الوسائط",
    assetsBranding: "الملفات والهوية",
    manageLibrary: "إدارة المكتبة",
    viewMedia: "عرض الوسائط",
    support: "الدعم",
    contactMessages: "رسائل التواصل",
    viewMessages: "عرض الرسائل",
    manageSupport: "إدارة الدعم",
    engagementScore: "درجة التفاعل",
    activeUsers: "المستخدمون النشطون",
    avgTime: "متوسط الوقت",
    scroll: "التمرير",
    returnRate: "معدل الزوار العائدين",
    days7: "آخر 7 أيام",
    days30: "آخر 30 يوم",
    interactions: "التفاعلات",
    conversions: "التحويلات",
    likes: "إعجابات",
    shares: "مشاركات",
    commentsLabel: "تعليقات",
    rate: "النسبة",
    bounce: "نسبة الارتداد",
    topPerforming: "أفضل المقالات أداءً",
    byViewsEngagement: "حسب المشاهدات والتفاعل والتحويلات",
    byViews: "حسب المشاهدات",
    byEngagement: "حسب التفاعل",
    views: "مشاهدة",
    score: "الدرجة",
    trafficSources: "مصادر الزيارات",
    last30Days: "آخر 30 يوم",
    recentActivity: "النشاط الأخير",
    latestUpdates: "آخر التحديثات والأحداث",
    noArticles: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
    noTraffic: "لا توجد بيانات زيارات بعد. ستتراكم خلال أيام من نشر المقالات.",
    noActivity: "لا يوجد نشاط حديث.",
    newArticlePublished: "مقالة جديدة نُشرت",
    newComment: "تعليق جديد",
    newSubscriber: "مشترك جديد",
    onArticle: "على المقالة",
    unknown: "غير معروف",
  },

  articles: {
    manageApproveArticles: "إدارة المقالات والموافقة عليها",
    pendingApprovalTab: "بانتظار الموافقة",
    published: "منشور",
    allArticles: "كل المقالات",
    noPending: "لا توجد مقالات بانتظار الموافقة. سنخبرك عند وصول مقالة جديدة.",
    noPublished: "لا توجد مقالات منشورة بعد.",
    noArticlesYet: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
    created: "تاريخ الإنشاء",
    pendingApprovalStatus: "بانتظار الموافقة",
    statusPublished: "منشور",
    statusDraft: "مسودة",
    statusScheduled: "مجدول",
    statusWriting: "قيد الكتابة",
    statusArchived: "مؤرشف",
    words: "كلمة",
    minRead: "دقيقة قراءة",
    tag: "وسم",
    tags: "وسوم",
    preview: "معاينة",
    approve: "موافقة",
    requestChanges: "طلب تعديلات",
    approving: "جاري الموافقة…",
    approveArticle: "الموافقة على المقالة",
    backToArticles: "العودة للمقالات",
    approveConfirm: "تأكيد الموافقة على المقالة؟",
    approveFailed: "ما تمت الموافقة على المقالة. جرّب مرة أخرى.",
    requestFailed: "ما تم إرسال طلب التعديل. جرّب مرة أخرى.",
    errorOccurred: "حدث خطأ",
    basicContent: "المحتوى الأساسي",
    titleSlugExcerpt: "العنوان والرابط والملخص والبيانات",
    title: "العنوان",
    slug: "الرابط",
    excerpt: "الملخص",
    status: "الحالة",
    datePublished: "تاريخ النشر",
    inLanguage: "اللغة",
    articleContent: "محتوى المقالة",
    fullArticleBody: "نص المقالة كاملاً",
    format: "التنسيق",
    formatLabel: "التنسيق",
    wordsCount: "كلمة",
    wordCount: "عدد الكلمات",
    readingTime: "وقت القراءة",
    contentDepth: "عمق المحتوى",
    characters: "حرف",
    credentials: "المؤهلات",
    relationships: "العلاقات",
    clientCategoryAuthor: "العميل والتصنيف والكاتب والوسوم",
    client: "العميل",
    category: "التصنيف",
    author: "الكاتب",
    featuredImage: "الصورة الرئيسية",
    mainArticleImage: "صورة المقالة الرئيسية",
    noImage: "لا توجد صورة",
    altText: "النص البديل",
    caption: "التسمية التوضيحية",
    imageGallery: "معرض الصور",
    imagesCount: "صورة",
    galleryImage: "صورة المعرض",
    min: "دقيقة",
    seoMeta: "بيانات البحث",
    searchEngineOpt: "تحسين محركات البحث",
    seoTitle: "عنوان البحث",
    seoTitleLabel: "عنوان البحث",
    seoDescription: "وصف البحث",
    seoDescriptionLabel: "وصف البحث",
    metaRobots: "إعدادات الروبوتات",
    canonicalUrl: "الرابط الأساسي",
    openGraph: "مشاركة الشبكات",
    ogType: "نوع المشاركة",
    ogArticleAuthor: "كاتب المقالة",
    ogImage: "صورة المشاركة",
    ogPublishedTime: "وقت النشر للمشاركة",
    twitterCards: "بطاقات تويتر",
    twitterCard: "بطاقة تويتر",
    twitterCardType: "نوع بطاقة تويتر",
    twitterSite: "حساب تويتر",
    twitterCreator: "المنشئ",
    faqs: "الأسئلة الشائعة",
    questionsCount: "سؤال",
    relatedArticles: "مقالات ذات صلة",
    technicalSeo: "بيانات تقنية للبحث",
    sitemapSettings: "خريطة الموقع والإعدادات التقنية",
    sitemapPriority: "أهمية الصفحة في البحث",
    sitemapChangeFreq: "تكرار التحديث",
    breadcrumbPath: "مسار التصفح",
    jsonld: "بيانات البحث المنظمة",
    schemaOrg: "بيانات منظمة لجوجل",
    lastGenerated: "آخر تحديث",
    citations: "المراجع",
    sourcesCount: "مصدر",
    requestChangesTitle: "طلب تعديلات",
    feedbackLabel: "ملاحظاتك أو التعديلات المطلوبة",
    feedbackPlaceholder: "صف التعديلات التي تود رؤيتها...",
    feedbackSent: "سنرسل ملاحظاتك لفريق المحتوى.",
    cancel: "إلغاء",
    sendFeedback: "إرسال الملاحظات",
    sending: "جاري الإرسال…",
    pleaseProvideFeedback: "أضف ملاحظاتك",
    articleLabel: "المقالة:",
    publishedOn: "نُشر في",
    articlePreviewTitle: "معاينة المقالة",
    reviewBeforeApproval: "تفقد المقالة قبل الموافقة",
    socialSharing: "مشاركة على الشبكات الاجتماعية",
    twitterSharingDesc: "بيانات مشاركة تويتر",
    articlesCount: "مقالة",
  },

  content: {
    articlesProgress: "تقدم المقالات الشهري",
    monthlyQuota: "الحصة الشهرية",
    publishedThisMonth: "المقالات المنشورة هذا الشهر",
    recentArticles: "آخر المقالات",
    yourContentLibrary: "مكتبة المحتوى",
    thisMonth: "هذا الشهر",
  },

  media: {
    mediaLibrary: "الصور والملفات",
    viewMediaAssets: "كل الصور والشعارات الخاصة بنشاطك",
    totalMedia: "إجمالي الوسائط",
    totalMediaLabel: "إجمالي الوسائط:",
    totalSize: "الحجم الإجمالي",
    files: "ملف",
    filesCount: "ملف",
    brandingAssets: "أصول الهوية",
    mediaGallery: "معرض الوسائط",
    viewLogoSocial: "شاهد الشعار وصور التواصل",
    logo: "الشعار",
    openGraphImage: "صورة المشاركة",
    twitterCardImage: "صورة بطاقة تويتر",
    all: "الكل",
    logos: "شعار الشركة",
    posts: "صور المقالات",
    ogImages: "صور الغلاف",
    unused: "غير مستخدمة",
    usedInPlaces: "مستخدم في {n} مكان",
    notUsed: "غير مستخدمة",
    noMedia: "لا توجد ملفات بعد. ستظهر هنا الصور المستخدمة في مقالاتك.",
    emptyAll: "لا توجد ملفات بعد. ستظهر هنا كل الصور الخاصة بنشاطك.",
    emptyLogo: "لم يتم تحديد شعار للشركة بعد. عند رفع شعارك، سيظهر هنا.",
    emptyPost: "لا توجد صور مقالات بعد. عند نشر مقالات، ستظهر صورها هنا.",
    emptyCover: "لم تُحدَّد صورة غلاف لصفحة شركتك على مودونتي بعد. عند ربط الصورة، ستظهر هنا.",
    emptyUnused: "كل الصور مستخدمة — لا يوجد صور بدون ربط.",
    emptySearch: "لا توجد نتائج للبحث.",
  },

  analytics: {
    title: "تحليلات معمّقة",
    comprehensiveAnalytics:
      "اعرف من زوّارك، متى يتفاعلون، وكيف يقرؤون. القرارات أوضح بمعلومات حقيقية.",
    pageRolePill: "تحقيق عميق — يكمّل لوحة التحكم",

    // Timeframe selector
    timeframeLabel: "الفترة الزمنية",
    timeframe7: "7 أيام",
    timeframe30: "30 يوم",
    timeframe90: "90 يوم",

    // Section titles
    audienceSection: "من هم زوّارك؟",
    audienceSubtitle: "شخصيتهم البصرية وعلاقتهم بمحتواك.",
    behaviorSection: "كيف يتصرّفون؟",
    behaviorSubtitle: "عمق القراءة، الوقت، والتنقّل.",
    timingSection: "متى يتفاعلون؟",
    timingSubtitle: "أنماط النشاط الأسبوعي واليومي.",
    contentSection: "ماذا يضغطون؟",
    contentSubtitle: "الأزرار والروابط الأكثر تفاعلاً.",
    technicalSection: "تجربة الموقع التقنية",
    technicalSubtitle: "Core Web Vitals — مؤشرات أداء جوجل.",
    insightsSection: "ملاحظات قابلة للتنفيذ",
    insightsSubtitle: "نصائح ذكية مبنيّة على بياناتك الفعلية.",

    // Device
    deviceTitle: "الأجهزة",
    deviceMobile: "جوال",
    deviceTablet: "تابلت",
    deviceDesktop: "ديسكتوب",
    deviceUnknown: "غير معروف",

    // New vs returning
    audienceTypeTitle: "زوار جدد مقابل عائدين",
    newVisitors: "زوّار جدد",
    returningVisitors: "زوّار عائدون",
    audienceTypeHint:
      "العائدون = شخص شاهد أكثر من صفحة في نفس الفترة (أكثر التزاماً بمحتواك).",

    // Day of week + hour patterns
    dayOfWeekTitle: "نشاط حسب اليوم",
    dayOfWeekSubtitle: "متى ينشط جمهورك خلال الأسبوع.",
    hourOfDayTitle: "نشاط حسب الساعة",
    hourOfDaySubtitle: "أوقات الذروة خلال اليوم.",
    daySun: "أحد",
    dayMon: "إثنين",
    dayTue: "ثلاثاء",
    dayWed: "أربعاء",
    dayThu: "خميس",
    dayFri: "جمعة",
    daySat: "سبت",

    // Behavior
    bounceRateTitle: "نسبة الارتداد",
    bounceRateHint: "الزوار الذين غادروا فوراً.",
    timeOnPageTitle: "متوسط الوقت في الصفحة",
    scrollDepthTitle: "متوسط عمق التمرير",
    scrollDepthDistTitle: "توزيع عمق القراءة",

    // Generic
    last30d: "آخر 30 يوم",
    last7d: "آخر 7 أيام",
    last90d: "آخر 90 يوم",
    noTraffic: "لا توجد بيانات زيارات بعد. ستتراكم تدريجياً.",
    noAudience: "لا توجد بيانات زوار بعد.",
    noTimingData: "لا توجد بيانات وقت بعد.",
    noInsights: "نحتاج بيانات أكثر لتقديم ملاحظات. تابع نشاطك واطّلع لاحقاً.",

    coreWebVitals: "تجربة الزائر على الموقع",
    performanceMetrics: "متوسط 30 يوم",
    timeOnPage: "وقت الصفحة",
    scrollDepth: "عمق التمرير",
    completionRate: "نسبة الإكمال",
    readingTime: "وقت القراءة",
    conversions: "التحويلات",
    totalConversions: "إجمالي التحويلات",
    conversionTypes: "أنواع التحويلات",
    noConversions: "لا تحويلات بعد",
    campaignPerformance: "أداء الحملات",
    activeCampaigns: "الحملات النشطة",
    impressions: "مرات الظهور",
    clicks: "نقرات",
    views: "مشاهدة",
    users: "مستخدم",
    topClickedLinks: "أكثر الروابط نقرة",
    mostClickedLinks: "في المقالات",
    noLinkClickData: "لا توجد بيانات نقرات بعد.",
    topReferrers: "أهم المصادر",
    noReferrerData: "لا توجد بيانات مصادر بعد.",
    engaged: "تفاعل",
    bounced: "ارتداد",
    lcp: "سرعة ظهور المحتوى",
    cls: "ثبات الصفحة",
    inp: "سرعة الاستجابة",
    ttfb: "سرعة الخادم",
    tbt: "وقت الانشغال",
    sAvg: "ث متوسط",
    percentAvg: "% متوسط",
    topCtaClicks: "أكثر الأزرار نقرة",
    ctaClicksDesc: "الأزرار والروابط المتتبعة",
    noCtaData: "لا توجد بيانات نقرات بعد.",
    ctaTypeButton: "زر",
    ctaTypeLink: "رابط",
    ctaTypeForm: "نموذج",
    ctaTypeBanner: "لافتة",
    ctaTypePopup: "نافذة منبثقة",

    // Legacy — kept for backward compat with other pages
    views7d: "مشاهدات (7 أيام)",
    views30d: "مشاهدات (30 يوماً)",
    totalPageViews: "إجمالي المشاهدات",
    articles: "المقالات",
    client: "العميل",
    engagementRate: "نسبة التفاعل",
    conversionRate: "نسبة التحويل",
    trafficSources: "مصادر الزيارات",
    engagementMetrics: "التفاعل",
    userBehavior: "سلوك المستخدم",
    topPerformingArticles: "أفضل المقالات",
    articlesRankedByViews: "حسب المشاهدات (30 يوماً)",
    scroll: "تمرير",
    noArticles: "لا توجد مقالات بعد.",
    clientPageViews: "مشاهدات صفحة العميل",
    brandPageAnalytics: "صفحة العلامة والملف (30 يوماً)",
    totalClientViews: "إجمالي المشاهدات",
    uniqueVisitors: "زوار فريدون",
    scrollDepthDist: "توزيع عمق التمرير",
    sourceOrganic: "بحث جوجل",
    sourceDirect: "زيارة مباشرة",
    sourceReferral: "إحالة من موقع آخر",
    sourceSocial: "شبكات اجتماعية",
    sourcePaid: "إعلان مدفوع",
    sourceUnknown: "غير معروف",
  } as const,

  leads: {
    title: "العملاء المحتملون",
    trackQualify: "الزوار الأكثر تفاعلاً مع محتواك خلال الـ 30 يوم الأخيرة.",

    // KPI cards
    hotLeads: "اهتمام عالٍ",
    warmLeads: "اهتمام متوسط",
    coldLeads: "اهتمام منخفض",
    qualified: "مؤهلون للتواصل",
    avgScore: "متوسط الدرجة",
    highEngagement: "درجة ≥ 70 — أولوية تواصل عاجل",
    moderateEngagement: "درجة 40 إلى 69 — تابعهم",
    lowEngagement: "درجة أقل من 40 — تفاعل بسيط",
    readyForOutreach: "درجة ≥ 60 — وقت التواصل",
    outOf100: "من 100",

    // Filters + table
    leadsOverview: "القائمة",
    leadsCount: "عميل محتمل",
    all: "الكل",
    hot: "عالٍ",
    warm: "متوسط",
    cold: "منخفض",
    qualifiedFilter: "مؤهل",
    searchPlaceholder: "ابحث بالاسم أو البريد…",
    showingPagedHint: "نعرض أعلى {n} درجة — استخدم البحث للوصول للأقدم.",

    contact: "جهة الاتصال",
    level: "المستوى",
    score: "الدرجة",
    pages: "صفحات",
    timeMin: "وقت (دقيقة)",
    interactions: "تفاعلات",
    conversions: "تحويلات",
    lastActive: "آخر نشاط",

    // Empty states
    noLeadsFound: "لا يوجد عملاء محتملون بعد",
    noLeadsHint: "اضغط \"تحديث الدرجات\" لحساب نقاط الزوار بناءً على تفاعلهم مع المحتوى.",
    noSearchResults: "لا توجد نتائج للبحث",
    noFilterResults: "لا يوجد عملاء في هذا الفلتر",

    noContact: "لا يوجد اتصال",
    anonymous: "زائر مجهول",
    unqualified: "غير مؤهل",
    qualifiedBadge: "مؤهل",

    // Refresh
    refreshScores: "تحديث الدرجات",
    refreshing: "جارٍ التحديث…",
    refreshSuccess: "تم تحديث {n} عميل · حُذف {d} قديم",
    refreshScoresError: "ما تم تحديث الدرجات. جرّب مرة أخرى.",
    never: "لم يُحسب بعد",
    lastRefreshed: "آخر تحديث",
    refreshedJustNow: "الآن",
    refreshedMinutesAgo: "منذ {n} دقيقة",
    refreshedHoursAgo: "منذ {n} ساعة",
    refreshedDaysAgo: "منذ {n} يوم",

    // Export
    exportCsv: "CSV",
    exporting: "…",
    exported_toast: "تم تصدير الملف",
    exportFailed: "ما تم التصدير. جرّب مرة أخرى.",

    // Detail drawer
    detailsTitle: "تفاصيل العميل المحتمل",
    contactInfo: "بيانات التواصل",
    scoreBreakdown: "تفاصيل الدرجة",
    scoreView: "مشاهدة الصفحات",
    scoreTime: "الوقت في الصفحات",
    scoreInteraction: "التفاعلات (نقرات CTA)",
    scoreConversion: "التحويلات",
    activitySection: "النشاط في آخر 30 يوم",
    timeSpentLabel: "إجمالي الوقت",
    pagesViewedLabel: "صفحات مشاهَدة",
    interactionsLabel: "تفاعلات",
    conversionsLabel: "تحويلات",
    lastActivityLabel: "آخر نشاط",
    contactCta: "تواصل عبر البريد",
    whatsappCta: "تواصل عبر واتساب",
    noContactMethods: "لا توجد بيانات تواصل لهذا الزائر بعد.",

    // KPI info popovers
    howScoreWorksTitle: "ما اللي يرفع الدرجة؟",
    howScoreWorksIntro: "كل زائر له درجة من 100 بناءً على 4 سلوكيات:",
    factor1: "📄 يقرأ مقالاتك",
    factor2: "⏱️ يقضي وقت في صفحاتك",
    factor3: "🖱️ يضغط على أزرارك",
    factor4: "✅ يحوّل (نموذج، اشتراك، شراء)",
    formulaLine: "كلما زاد تفاعله، ارتفعت درجته.",
    windowNote: "نقيس آخر 30 يوم فقط. الزوار الخامدين يُحذفون تلقائياً.",

    infoHighTitle: "اهتمام عالٍ — مَن هو؟",
    infoHighDesc: "الزائر اللي يتفاعل معك بقوة:",
    infoHighExample:
      "• قرأ مقالات متعددة\n• قضى وقت طويل\n• ضغط على روابطك\n• وغالباً حوّل (سجّل، طلب، اشترى)\n\nهؤلاء أولوية تواصل عاجل.",

    infoMediumTitle: "اهتمام متوسط — مَن هو؟",
    infoMediumDesc: "الزائر المهتم لكن لسه ما اتخذ خطوة:",
    infoMediumExample:
      "• يقرأ ويتفقّد\n• ضغط على بعض الأزرار\n• لكن ما حوّل بعد\n\nقريب من 'عالي' — تابعه بمحتوى أو رسالة.",

    infoLowTitle: "اهتمام منخفض — مَن هو؟",
    infoLowDesc: "الزائر العابر:",
    infoLowExample:
      "• شاف صفحة أو اثنين\n• بدون تفاعل واضح\n• ممكن قارئ صدفة\n\nلو ما رجع خلال 30 يوم، يُحذف تلقائياً عند التحديث.",

    infoQualifiedTitle: "مؤهل للتواصل — وش يعني؟",
    infoQualifiedDesc: "الزائر اللي وصل لمستوى تستحق فيه التواصل:",
    infoQualifiedNote:
      "ممكن يكون 'عالي' أو 'متوسط مرتفع' — المهم إنه يهتم ومتابع لمحتواك. اتصل بيه أو ابعث له رسالة.",

    infoAvgTitle: "متوسط الدرجة — وش يعني؟",
    infoAvgDesc: "رقم يقيس صحة جمهورك ككل:",
    infoAvgExample:
      "• عالي → جمهورك متفاعل، محتواك يجذب\n• منخفض → المحتوى يحتاج تطوير، أو الجمهور غير المستهدف",
    infoAvgInterpret:
      "نحسبه كمتوسط لكل العملاء المحتملين الحاليين (آخر 30 يوم).",

    infoButton: "كيف يُحتسب؟",
    closeBtn: "إغلاق",
  },

  subscribers: {
    title: "مشتركو النشرة",
    manageNewsletter: "كل من اشترك في نشرتك ووافقاته الخصوصية في مكان واحد.",

    // Filters
    all: "الكل",
    active: "نشط",
    subscribedUsers: "يستقبلون نشرتك",
    unsubscribed: "ألغوا الاشتراك",
    leftTheList: "غادروا القائمة",
    withConsentOnly: "بموافقة الخصوصية",

    // KPI cards
    gdprConsent: "موافقة الخصوصية",
    consentLabel: "وافقوا على استلام النشرة",
    thisMonth: "هذا الشهر",
    newSubscribers: "اشتركوا حديثاً",
    total: "الإجمالي",
    allSubscribers: "كل سجلّات المشتركين",

    // Table + search
    subscribersList: "القائمة",
    subscribersCount: "مشترك",
    showingPagedHint: "نعرض أحدث {n} سجل — استخدم البحث للوصول للأقدم.",
    searchPlaceholder: "ابحث بالبريد أو الاسم…",
    exportCsv: "تصدير CSV",
    exporting: "جارٍ التصدير…",

    // Columns
    email: "البريد الإلكتروني",
    subscribedAt: "تاريخ الاشتراك",
    status: "الحالة",
    name: "الاسم",
    consent: "الموافقة",
    actions: "الإجراءات",
    noConsent: "بدون موافقة",
    yesConsent: "موثّقة",

    // Empty states
    noSubscribers: "لا يوجد مشتركون بعد",
    noSubscribersHint: "سيظهر هنا كل من يشترك في نشرتك من زوّار مقالاتك.",
    noSearchResults: "لا توجد نتائج للبحث",
    noSearchHint: "جرّب كلمات بحث مختلفة أو ألغِ الفلاتر.",
    noFilterResults: "لا يوجد مشتركون في هذا الفلتر",

    // Bulk actions
    selected: "مُحدَّد",
    selectAll: "تحديد الكل",
    bulkUnsubscribe: "إلغاء اشتراك المحدد",
    bulkDelete: "حذف المحدد",
    clearSelection: "إلغاء التحديد",

    // Confirmations + toasts
    confirmUnsubscribeOne: "إلغاء اشتراك هذا المشترك؟",
    confirmDeleteOne: "حذف نهائي لهذا المشترك؟ لا يمكن التراجع.",
    confirmBulkUnsubscribe: "إلغاء اشتراك {n} مشترك؟",
    confirmBulkDelete: "حذف {n} مشترك نهائياً؟ لا يمكن التراجع.",
    confirmYes: "نعم، تنفيذ",
    cancel: "إلغاء",

    unsubscribed_toast: "تم إلغاء الاشتراك",
    resubscribed_toast: "تم تفعيل الاشتراك",
    deleted_toast: "تم الحذف",
    bulkUnsubscribed_toast: "تم إلغاء اشتراك {n} مشترك",
    bulkDeleted_toast: "تم حذف {n} مشترك",
    exported_toast: "تم تصدير الملف",

    unsubscribeFailed: "ما تم إلغاء الاشتراك. جرّب مرة أخرى.",
    resubscribeFailed: "ما تمت إعادة الاشتراك. جرّب مرة أخرى.",
    deleteFailed: "ما تم الحذف. جرّب مرة أخرى.",
    exportFailed: "ما تم التصدير. جرّب مرة أخرى.",
    bulkFailed: "ما تمت العملية. جرّب مرة أخرى.",

    // Detail drawer
    detailsTitle: "تفاصيل المشترك",
    contactInfo: "بيانات التواصل",
    timeline: "السجلّ الزمني",
    consentInfo: "موافقة الخصوصية",
    consentGivenAt: "تاريخ الموافقة",
    subscribedSince: "مشترك منذ",
    unsubscribedAt: "أَلغَى الاشتراك في",
    preferencesLabel: "التفضيلات",
    noPreferences: "لا توجد تفضيلات مخصّصة.",
    actionUnsubscribe: "إلغاء الاشتراك",
    actionResubscribe: "إعادة التفعيل",
    actionDelete: "حذف نهائي",
  },

  campaigns: {
    beta: "قريباً",

    // Hero
    soonBadge: "قريباً",
    heroTitle: "حملاتك الإيميلية، بلمسة احترافية",
    heroSubtitle: "أنت تشارك الفكرة، فريقنا يصمّم ويرسل، والنتائج تصلك مباشرة.",

    // Quota strip
    yourQuota: "رصيدك من الحملات",
    perMonth: "حملة شهرياً",
    includedInPlan: "مشمولة في باقتك الحالية",
    extraCampaign: "حملة إضافية",
    onDemandPricing: "بسعر مرن حسب الطلب",

    // 3 reach tiers
    reachTitle: "اختر مدى وصول حملتك",
    reachSubtitle: "ثلاثة مستويات تمنحك تحكّماً كاملاً في جمهورك المستهدف.",
    tier1Title: "مشتركو نشرتك",
    tier1Tag: "ضمن باقتك",
    tier1Desc: "تصلهم رسائلك مباشرة. بنوها بنفسك من زوّار مقالاتك.",
    tier2Title: "جمهور قطاعك",
    tier2Tag: "إضافة مدفوعة",
    tier2Desc: "وسّع وصولك لمشتركين مهتمين بمجال نشاطك من عملاء مودونتي الآخرين.",
    tier3Title: "كامل قاعدة مودونتي",
    tier3Tag: "أعلى تأثير",
    tier3Desc: "أوسع شبكة وصول. لإطلاقات كبيرة وحملات موسمية.",

    // Workflow
    workflowTitle: "كيف تعمل الحملة؟ خمس خطوات.",
    workflowSubtitle: "بدون تعقيد. أنت تطلب، نحن ننفّذ.",
    step1Title: "أنت تطلب",
    step1Desc: "أرسل فكرة الصورة ونص الإيميل بكلماتك.",
    step2Title: "نحن نصمّم",
    step2Desc: "فريقنا يجهّز التصميم النهائي بهوية علامتك.",
    step3Title: "أنت توافق",
    step3Desc: "تراجع وتوافق بضغطة زر.",
    step4Title: "ننشر بأمان",
    step4Desc: "نطلق الحملة عبر بنية موثوقة.",
    step5Title: "تتابع النتائج",
    step5Desc: "فتح، نقر، تحويل — كل شيء أمامك مباشرة.",

    // Social proof — verifiable evidence
    proofTitle: "الأرقام تتكلّم — من مصادر عالمية معتمدة",
    proofSubtitle:
      "هذي ليست أرقامنا. مصادر تسويقية مستقلّة نقدّم لك روابطها مباشرة لتتحقّق بنفسك.",
    proofVerifyLink: "تحقّق من المصدر",

    proof1Stat: "‏$36 – $45",
    proof1Title: "عائد كل دولار تنفقه في الإيميل",
    proof1Desc: "أعلى ROI بين كل القنوات التسويقية الرقمية.",
    proof1Source: "Litmus — 2025 State of Email",

    proof2Stat: "40×",
    proof2Title: "أكثر فعالية من Facebook + Twitter مجتمعَيْن",
    proof2Desc: "في جذب عملاء جدد، بحسب دراسة McKinsey & Company.",
    proof2Source: "McKinsey & Company",

    proof3Stat: "52٪",
    proof3Title: "من المستهلكين اشتروا مباشرة من إيميل",
    proof3Desc: "الإيميل يتفوّق على Social Posts بـ 13٪ وعلى Social Ads بـ 11٪.",
    proof3Source: "HubSpot — State of Marketing",

    proof4Stat: "8 سنوات",
    proof4Title: "متتالية في المركز الأول للـ ROI",
    proof4Desc: "بحسب جمعية البيانات والتسويق البريطانية (DMA).",
    proof4Source: "DMA — Email Benchmarking 2024",

    proofFooter:
      "نحن نشاركك هذه المصادر بشفافية لأن قرار التسويق يستحق الحقيقة، لا الوعود.",

    // Features strip
    featuresTitle: "لماذا حملات مودونتي؟",
    feat1Title: "تصميم احترافي جاهز",
    feat1Desc: "بدون قوالب جاهزة باهتة. كل تصميم خاص بك.",
    feat2Title: "نتائج مباشرة",
    feat2Desc: "إحصائيات لحظية: من فتح، من قرأ، من ضغط.",
    feat3Title: "بنية موثوقة",
    feat3Desc: "إرسال آمن مع نسبة وصول عالية للبريد الرئيسي.",
    feat4Title: "متوافق مع الخصوصية",
    feat4Desc: "نلتزم بقوانين حماية البيانات في السعودية ومصر.",

    // CTA
    ctaTitle: "كن من أول من يطلق حملته معنا",
    ctaSubtitle: "احجز اهتمامك الآن. فريقنا يتواصل معك أول ما تنطلق الميزة.",
    ctaPrimary: "أنا مهتم — احجز لي مكاناً",
    ctaSecondary: "أرغب بحملات إضافية",
    ctaSubmitting: "جارٍ تسجيل اهتمامك…",
    ctaSuccess: "تم استلام طلبك. فريقنا يتواصل معك خلال 24 ساعة.",
    ctaError: "ما تمّ التسجيل. جرّب مرة أخرى.",
    ctaAlreadyRegistered: "اهتمامك مسجّل بالفعل. شكراً لك!",

    // Footer note
    launchNote: "هذه الميزة قيد التطوير. الواجهة هنا تعرض ما ستحصل عليه عند الإطلاق.",

    // Legacy keys (used by analytics components kept for future revival)
    campaignPerformance: "أداء الحملات",
    detailedMetrics: "مقاييس تفصيلية لكل حملة",
    noCampaignData: "لا توجد بيانات حملات بعد.",
    noCampaignHint: "لبدء التتبع، أضف وسوم لروابط حملاتك.",
    utmAnalysis: "تحليل روابط الحملات",
    trackBySource: "حسب المصدر والوسيط والحملة",
    noUtmData: "لا توجد بيانات تتبع روابط بعد.",
    source: "المصدر",
    medium: "الوسيط",
    campaign: "الحملة",
    type: "النوع",
    impressions: "مرات الظهور",
    clicks: "النقرات",
    ctr: "نسبة النقر إلى الظهور",
    cvr: "نسبة التحويل",
    cost: "التكلفة",
    roi: "العائد على الإنفاق",
    conversions: "التحويلات",
    visits: "الزيارات",
    conversionRate: "نسبة التحويل",
  },

  comments: {
    title: "مراجعة التعليقات",
    reviewModerate: "وافِق أو ارفض تعليقات قرّائك. ردّ مباشرة عليهم لتشجيع المحادثة.",

    // KPI cards
    pending: "بانتظار المراجعة",
    awaitingReview: "بانتظار المراجعة",
    approved: "معتمد",
    publishedComments: "تعليقات منشورة",
    rejected: "مرفوض",
    rejectedComments: "تعليقات مرفوضة",
    deletedKpi: "محذوفة",
    deletedHint: "تعليقات نقلتها للأرشيف",
    total: "الإجمالي",
    all: "الكل",
    allComments: "كل التعليقات النشطة",
    activeOnly: "النشطة فقط (بدون المحذوفة)",
    commentsCount: "تعليق",

    // Filters + table
    listTitle: "القائمة",
    searchPlaceholder: "ابحث في التعليق أو الكاتب أو المقال…",
    fromArticle: "في مقال",
    selected: "مُحدَّد",
    selectAll: "تحديد الكل",
    clearSelection: "إلغاء التحديد",

    // Actions
    approveComment: "موافقة",
    rejectComment: "رفض",
    deleteComment: "حذف",
    restoreComment: "استرجاع",
    approveSelected: "الموافقة على المحدد",
    rejectSelected: "رفض المحدد",
    confirmDeleteOne: "حذف هذا التعليق؟ يمكن استرجاعه لاحقاً.",
    confirmYes: "نعم، تنفيذ",
    cancel: "إلغاء",

    // Toasts
    approved_toast: "تم النشر",
    rejected_toast: "تم الرفض",
    deleted_toast: "تم الحذف (يمكن استرجاعه)",
    restored_toast: "تم الاسترجاع",
    bulkApproved_toast: "تم نشر {n} تعليق",
    bulkRejected_toast: "تم رفض {n} تعليق",
    approveFailed: "ما تمت الموافقة. جرّب مرة أخرى.",
    rejectFailed: "ما تم الرفض. جرّب مرة أخرى.",
    deleteFailed: "ما تم الحذف. جرّب مرة أخرى.",
    bulkApproveFailed: "ما تمت الموافقة الجماعية. جرّب مرة أخرى.",
    bulkRejectFailed: "ما تم الرفض الجماعي. جرّب مرة أخرى.",

    // Empty states
    noCommentsFound: "لا توجد تعليقات بعد",
    noCommentsHint: "ستظهر هنا تعليقات قرّائك على مقالاتك. كلما زاد التفاعل، زاد الأثر.",
    noSearchResults: "لا توجد نتائج للبحث",
    noFilterResults: "لا توجد تعليقات في هذا الفلتر",

    // Author info
    anonymous: "زائر مجهول",
    noEmail: "لا يوجد بريد",
    replies: "رد",
    replyTo: "رد على:",

    // Detail drawer
    detailsTitle: "تفاصيل التعليق",
    authorSection: "بيانات الكاتب",
    authorName: "الاسم",
    authorEmail: "البريد",
    contactCta: "تواصل عبر البريد",
    commentSection: "نص التعليق",
    parentSection: "تعليق رد عليه",
    statsSection: "تفاعل التعليق",
    likesLabel: "إعجابات",
    dislikesLabel: "عدم إعجاب",
    repliesLabel: "ردود",
    timelineSection: "الزمن",
    createdAt: "تاريخ النشر",
    updatedAt: "آخر تحديث",
    editedBadge: "مُعدَّل",
  },

  faqs: {
    title: "الأسئلة الشائعة",
    description:
      "أسئلة مقترحة من فريق مودونتي وأخرى من زوّار مقالاتك — وافِق أو ارفض.",

    // KPI cards
    pending: "بانتظار الموافقة",
    published: "منشورة",
    rejected: "مرفوضة",
    total: "الإجمالي",
    fromReadersKpi: "من زوّار مقالاتك",
    awaitingApproval: "بانتظار موافقتك",
    publishedFaqs: "أسئلة منشورة",
    rejectedFaqs: "أسئلة مرفوضة",
    allFaqs: "كل الأسئلة",
    fromReadersHint: "أسئلة من قرّاء حقيقيين",

    // Filters + table
    listTitle: "القائمة",
    all: "الكل",
    faqsCount: "سؤال",
    searchPlaceholder: "ابحث في السؤال أو المقال…",
    fromArticle: "من مقال",
    fromReader: "من زائر",
    submittedBy: "أرسله",
    contactReaderViaEmail: "تواصل مع الزائر",

    // Actions
    approve: "نشر",
    reject: "رفض",
    approving: "جاري النشر…",
    rejecting: "جاري الرفض…",
    restore: "إعادة للانتظار",
    restored_toast: "تمت الإعادة لـ 'بانتظار الموافقة'",
    editAnswer: "تعديل الإجابة",
    editPublished: "تعديل النص",
    answerLabel: "الإجابة",
    answerPlaceholder: "اكتب إجابتك هنا…",
    save: "حفظ التعديل",
    saving: "جاري الحفظ…",
    cancel: "إلغاء",
    answerRequired: "اكتب إجابة قبل النشر",

    // Bulk
    selected: "مُحدَّد",
    bulkPublish: "نشر المحدد",
    bulkReject: "رفض المحدد",
    clearSelection: "إلغاء التحديد",
    confirmBulkPublish: "نشر {n} سؤال (الذين عندهم إجابات فقط)؟",
    confirmBulkReject: "رفض {n} سؤال؟",
    confirmYes: "نعم، تنفيذ",
    bulkPublished_toast: "تم نشر {n} سؤال",
    bulkRejected_toast: "تم رفض {n} سؤال",

    // Toasts
    approved_toast: "تم النشر",
    rejected_toast: "تم الرفض",
    saved_toast: "تم الحفظ",
    approveFailed: "ما تم النشر. جرّب مرة أخرى.",
    rejectFailed: "ما تم الرفض. جرّب مرة أخرى.",
    saveFailed: "ما تم الحفظ. جرّب مرة أخرى.",
    bulkFailed: "ما تمت العملية. جرّب مرة أخرى.",

    // Empty states
    noFaqs: "لا توجد أسئلة بعد",
    noFaqsHint: "ستظهر هنا الأسئلة المقترحة من فريق مودونتي + أسئلة زوّار مقالاتك.",
    noSearchResults: "لا توجد نتائج للبحث",
    noFilterResults: "لا توجد أسئلة في هذا الفلتر",

    // Source labels
    source: "المصدر",
    sourceChatbot: "من المساعد الذكي",
    sourceUser: "من زائر مسجَّل",
    sourceManual: "أعدّها فريق مودونتي",
    sourceUnknown: "غير محدّد",

    // Detail drawer
    detailsTitle: "تفاصيل السؤال",
    questionLabel: "السؤال",
    submitterLabel: "بيانات المُرسِل",
    submitterName: "الاسم",
    submitterEmail: "البريد",
    submittedAt: "تاريخ الإرسال",
    lastUpdated: "آخر تعديل",
    articleLink: "افتح المقال",
    needsAnswerHint: "هذا السؤال من زائر — لازم تكتب إجابة قبل النشر.",
  },

  questions: {
    title: "أسئلة الزوار",
    description:
      "بريد القرّاء — أسئلة وصلت من زوار مقالاتك. ردّ بنقرة، يصلهم الرد عبر الإيميل تلقائياً.",
    pageHint: "هذي الصفحة للأسئلة من المساعد الذكي + الزوار المسجَّلين فقط — أسئلة فريق مودونتي تجد في 'الأسئلة الشائعة'.",

    // KPI cards
    pending: "بانتظار الرد",
    answered: "تم الرد",
    rejected: "مرفوض",
    total: "الإجمالي",
    awaitingReply: "أولوية: ردّ سريعاً",
    publishedReplies: "ردود منشورة",
    rejectedHint: "أسئلة لن تُجاب",
    allQuestions: "كل الأسئلة (نشطة + مرفوضة)",

    // Filters + table
    listTitle: "القائمة",
    questionsCount: "سؤال",
    searchPlaceholder: "ابحث في السؤال أو الكاتب أو المقال…",
    fromArticle: "من مقال",
    fromReader: "من زائر",
    sourceChatbot: "من المساعد الذكي",
    sourceUser: "من زائر مسجَّل",

    // Actions
    reply: "أرسل الرد",
    replyPlaceholder: "اكتب ردك هنا…",
    replying: "جارٍ الإرسال…",
    rejectQuestion: "رفض السؤال",
    rejectingQuestion: "جارٍ الرفض…",
    restoreQuestion: "إعادة للانتظار",
    confirmReject: "رفض هذا السؤال؟ يمكن إرجاعه لاحقاً.",
    confirmYes: "نعم، تنفيذ",
    cancel: "إلغاء",
    answerRequired: "اكتب ردك قبل الإرسال",

    // Toasts
    replySuccess: "تم إرسال الرد للزائر عبر الإيميل",
    replyFailed: "ما تم إرسال الرد. جرّب مرة أخرى.",
    rejected_toast: "تم الرفض",
    restored_toast: "تمت الإعادة لـ 'بانتظار الرد'",
    rejectFailed: "ما تم الرفض. جرّب مرة أخرى.",

    // Submitter
    submitter: "المرسل",
    anonymous: "زائر مجهول",
    noEmail: "لا يوجد بريد",
    yourReply: "ردك",

    // Empty states
    noQuestions: "لا توجد أسئلة بعد",
    noQuestionsHint:
      "ستظهر هنا الأسئلة من زوار مقالاتك (المساعد الذكي أو نموذج 'اسأل عن المقال').",
    noSearchResults: "لا توجد نتائج للبحث",
    noFilterResults: "لا توجد أسئلة في هذا الفلتر",

    // Detail drawer
    detailsTitle: "تفاصيل السؤال",
    submitterSection: "بيانات الزائر",
    submitterName: "الاسم",
    submitterEmail: "البريد",
    contactCta: "تواصل عبر الإيميل",
    questionSection: "نص السؤال",
    answerSection: "الرد المنشور",
    articleSection: "المقال",
    timelineSection: "الزمن",
    submittedAt: "وصل في",
    repliedAt: "تم الرد في",
  },

  support: {
    title: "رسائل الدعم",
    manageContact: "كل رسائل التواصل من الزوار، مع إمكانية الرد بالإيميل وحفظ الردود.",
    pageHint:
      "هذي الرسائل وصلتك من نموذج «تواصل معنا» في الموقع. كل رسالة فيها بيانات المرسل والموضوع، وتقدر ترد عليه مباشرة من هنا — الرد ينحفظ ويرسل بريد للزائر.",
    all: "الكل",
    new: "جديد",
    archived: "مؤرشف",
    unreadMessages: "ما تم فتحها بعد",
    read: "مقروء",
    messagesRead: "تم الاطلاع عليها",
    replied: "تم الرد",
    messagesReplied: "أرسلت لها رد",
    total: "الإجمالي",
    allMessages: "كل الرسائل",
    archivedHint: "خارج صندوق الوارد",
    messages: "الرسائل",
    messageDetails: "تفاصيل الرسالة",
    selectToView: "اختر رسالة لعرض تفاصيلها",
    noMessagesFound: "لا توجد رسائل بعد.",
    noMatchSearch: "ما لقيت رسائل تطابق بحثك.",
    searchPlaceholder: "ابحث في الاسم، الإيميل، الموضوع، أو نص الرسالة…",
    showing: "إظهار",
    of: "من",
    from: "من",
    subject: "الموضوع",
    received: "تاريخ الاستلام",
    message: "الرسالة",
    referrer: "صفحة الإحالة",
    markRead: "مقروء",
    markReplied: "تم الرد",
    markArchived: "أرشفة",
    markNew: "إعادة لـ«جديد»",
    delete: "حذف",
    deleteConfirm: "تأكيد حذف هذه الرسالة؟",
    bulkDeleteConfirm: "تأكيد حذف الرسائل المحددة؟",
    updateFailed: "ما تم تحديث الرسالة. جرّب مرة أخرى.",
    updateSuccess: "تم تحديث حالة الرسالة.",
    deleteFailed: "ما تم حذف الرسالة. جرّب مرة أخرى.",
    deleteSuccess: "تم حذف الرسالة.",
    bulkUpdateSuccess: "تم تحديث الرسائل المحددة.",
    bulkDeleteSuccess: "تم حذف الرسائل المحددة.",
    selected: "محدّدة",
    selectAll: "تحديد الكل",
    clearSelection: "إلغاء التحديد",
    bulkActions: "إجراءات",
    bulkMarkRead: "تعليم كمقروءة",
    bulkArchive: "أرشفة",
    bulkDelete: "حذف",
    reply: "ردّك على الزائر",
    replyPlaceholder: "اكتب ردّك هنا…",
    yourReply: "ردك",
    sendReply: "إرسال الرد",
    replyViaEmail: "إرسال الرد عبر البريد للزائر",
    replySuccess: "تم إرسال الرد بنجاح.",
    replyFailed: "ما تم إرسال الرد. جرّب مرة أخرى.",
    replySavedEmailFailed: "تم حفظ الرد، لكن ما تم إرسال البريد.",
    metaSection: "تفاصيل الإرسال",
    ipAddress: "عنوان IP",
    userAgent: "المتصفح",
    sentAt: "وصلت",
    readAt: "فُتحت",
    repliedAt: "أُجيب عليها",
    statusBadge: {
      new: "جديد",
      read: "مقروء",
      replied: "تم الرد",
      archived: "مؤرشف",
    },
  },

  profile: {
    title: "معلومات الشركة",
    description: "تعديل بيانات الشركة والتواصل",
    basicInfo: "البيانات الأساسية",
    name: "اسم الشركة",
    legalName: "الاسم القانوني",
    alternateName: "الاسم البديل",
    url: "الموقع الإلكتروني",
    slogan: "الشعار",
    organizationDescription: "وصف الشركة",
    contactInfo: "معلومات التواصل",
    contactType: "نوع جهة الاتصال",
    address: "العنوان",
    addressStreet: "الشارع",
    addressCity: "المدينة",
    addressCountry: "الدولة",
    addressPostalCode: "الرمز البريدي",
    addressRegion: "المنطقة",
    addressNeighborhood: "الحي",
    addressBuildingNumber: "رقم المبنى",
    addressAdditionalNumber: "الرقم الإضافي",
    saudiGulf: "السجل التجاري والضرائب",
    commercialRegistrationNumber: "رقم السجل التجاري",
    vatID: "الرقم الضريبي (زاتكا)",
    taxID: "الرقم الضريبي",
    legalForm: "الشكل القانوني",
    business: "معلومات الأعمال",
    industry: "القطاع",
    targetAudience: "الجمهور المستهدف",
    organizationType: "نوع المنظمة",
    foundingDate: "تاريخ التأسيس",
    businessBrief: "نبذة عن الأعمال",
    socialProfiles: "الحسابات الاجتماعية",
    socialProfilesHint: "رابط واحد في كل سطر (لينكدإن، تويتر، فيسبوك)",
    seo: "بيانات البحث",
    seoTitle: "عنوان البحث",
    seoDescription: "وصف البحث",
    canonicalUrl: "الرابط الأساسي",
    canonicalUrlHint: "إذا نُسخت مقالتك في مكان آخر، هذا الرابط يخبر جوجل بالمصدر الأصلي.",
    twitter: "تويتر",
    twitterTitle: "عنوان تويتر",
    twitterDescription: "وصف تويتر",
    twitterSite: "@اسم_المستخدم",
    seoSettings: "إعدادات البحث",
    technicalProfile: "الملف التقني",
    platform: "المنصة",
    stagingUrl: "رابط الموقع التجريبي",
    seoGoals: "أهداف الظهور في البحث",
    primaryGoal: "الهدف الرئيسي",
    kpis: "مؤشرات النجاح (مثل: عدد الزوار، المبيعات)",
    goalsDisclaimer: "نساعدك نحدد الأولويات ونرتب الخطة. النتائج تتحقق تدريجياً وتتأثر بالمنافسة وجودة الموقع والاستمرارية — نعمل معك لأفضل نتيجة ممكنة دون وعد بأرقام أو مواعيد ثابتة.",
    successMetrics: "معايير النجاح",
    timeline: "الجدول الزمني",
    seoMetrics: "مقاييس البحث",
    domainAuthority: "قوة الموقع في البحث",
    backlinkCount: "عدد الروابط الخلفية",
    linkBuildingPolicy: "سياسة بناء الروابط",
    brandGuidelines: "إرشادات البراند",
    contentTone: "نبرة المحتوى",
    complianceConstraints: "قيود الامتثال",
    complianceIndustry: "قطاع الامتثال",
    restrictedClaims: "ادعاءات مقيدة",
    googleBusinessProfileUrl: "رابط ملف نشاطك التجاري على جوجل",
    forbiddenKeywords: "كلمات ممنوعة",
    forbiddenClaims: "ادعاءات ممنوعة",
    competitiveMentionsAllowed: "السماح بذكر المنافسين",
  },

  seo: {
    title: "معلومات مهمة",
    heroDescription:
      "«مدونتي» هي منصة تمكّن أصحاب الأعمال من الحصول على مقالات جاهزة ومتجددة ترفع ظهورهم على محركات البحث. ببساطة، هي تساعدك على نشر محتوى مدروس باستمرار دون الحاجة لأن تكتب بنفسك، مما يوفر لك الوقت ويعزز ظهور علامتك.",
    intake: "معلومات مهمة",
    competitors: "المنافسون",
    keywords: "الكلمات المفتاحية",
    project: "المشروع",
    addCompetitor: "إضافة منافس",
    addKeyword: "إضافة كلمة",
    name: "الاسم",
    url: "الرابط",
    notes: "ملاحظات",
    keyword: "الكلمة",
    intent: "النية",
    priority: "الأولوية",
    reason: "السبب",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    saveIntake: "حفظ الاستمارة",
    transactional: "معاملاتي",
    informational: "معلوماتي",
    commercial: "تجاري",
    goals: "الأهداف",
    budget: "الميزانية",
    contactPerson: "مَن نتواصل معه؟",
    reportingPreference: "شكل التقارير",
    weekly: "أسبوعي",
    monthly: "شهري",
    noCompetitors: "لا يوجد منافسون بعد.",
    noKeywords: "لا توجد كلمات مفتاحية بعد.",
    deleteConfirm: "تأكيد الحذف؟",
    keywordsTabNote: "أضف الكلمات المستهدفة من تبويب «الكلمات المفتاحية» أعلى الصفحة.",
  },

  settings: {
    profileSettings: "الملف والإعدادات",
    contactGtm: "التواصل وأدوات التتبع (اختياري)",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gtmContainerId: "معرّف Google Tag Manager (اختياري)",
    gtmHint: "إذا كنت تستخدم Google Tag Manager لتتبع الزوار، أدخل المعرّف هنا.",
    placeholderEmail: "example@mail.com",
    placeholderPhone: "+966...",
    placeholderGtm: "GTM-XXXXXXX",
    save: "حفظ",
    saving: "جاري الحفظ…",
    saved: "تم الحفظ.",
    updateFailed: "ما تم التحديث. جرّب مرة أخرى.",
    somethingWrong: "حدث خطأ.",

    // Page-level
    pageTitle: "الإعدادات",
    pageHint:
      "كل ما يخصّ حسابك في مكان واحد: حالة الاشتراك، تنبيهاتك، وكلمة المرور.",

    // Subscription
    subscriptionTitle: "الاشتراك",
    subscriptionHint: "حالة الباقة الحالية وتاريخ التجديد.",
    daysLeft: "يوم متبقّي",
    expiresOn: "ينتهي في",
    startedOn: "بدأ في",
    perYear: "سنوياً",
    statusActive: "نشط",
    statusInactive: "غير نشط",
    statusExpired: "منتهي",
    statusCancelled: "ملغى",
    paymentPaid: "مدفوع",
    paymentUnpaid: "غير مدفوع",
    paymentPending: "قيد الدفع",

    // Notifications
    notifications: "الإشعارات",
    notificationsDesc: "اختر ما تريد إشعارك به",
    notificationsHint:
      "نرسل لك إشعارات داخل اللوحة فقط — اختر الأحداث المهمة لك. تقدر تطفي أي شي مالك حاجة فيه.",
    articlePublished: "نشر مقالة جديدة",
    articleApprovedOption: "الموافقة على مقالة",
    commentsNew: "تعليقات جديدة",
    supportReplies: "ردود الدعم",

    // Password
    passwordCard: "كلمة المرور",
    passwordHint: "اختر كلمة قوية لا تقل عن 8 أحرف، ولا تشاركها مع أحد.",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    showPassword: "إظهار",
    hidePassword: "إخفاء",
    passwordChanged: "تم تغيير كلمة المرور بنجاح.",
    wrongPassword: "كلمة المرور الحالية غير صحيحة",
    passwordsMismatch: "كلمة المرور الجديدة وتأكيدها لا تتطابقان",
    passwordMinLength: "كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل",
    strengthWeak: "ضعيفة",
    strengthMedium: "متوسطة",
    strengthStrong: "قوية",
  },

  telegram: {
    cardTitle: "Telegram",
    cardHint: "استلم إشعارات engagement على تيليجرام مباشرة.",
    statusConnected: "مربوط",
    statusDisconnected: "غير مربوط",
    connectedSince: "تم الربط في",
    connect: "ربط حساب Telegram",
    disconnect: "فصل الربط",
    disconnectConfirm: "تأكيد فصل الربط؟ راح تتوقف الإشعارات.",
    disconnected: "تم فصل الربط.",
    sendTest: "إرسال رسالة اختبار",
    testSent: "تم إرسال الاختبار.",
    testFailed: "فشل إرسال الاختبار.",
    pairingTitle: "خطوات الربط",
    pairingStep1: "افتح الرابط:",
    pairingStep2: "اكتب /start في المحادثة",
    pairingStep3: "ارجع هنا، الكود تحت — أرسله للبوت في تيليجرام",
    pairingCode: "كود الربط",
    pairingExpires: "صالح حتى",
    generateCode: "توليد كود ربط",
    codeCopied: "تم نسخ الكود.",
    codeGenerated: "تم توليد الكود — أرسله للبوت في تيليجرام.",
    eventsTitle: "الإشعارات اللي تبغاها",
    eventsHint: "اختر بس الأحداث المهمة عشان ما تتزحم رسائلك.",
    eventsPickBeforePair:
      "تقدر تختار تفضيلاتك من الآن — لما تربط حسابك في تيليجرام، التفضيلات بتصير شغّالة فوراً.",
    selectAll: "تحديد الكل",
    selectNone: "إلغاء الكل",
    eventsSaved: "تم حفظ تفضيلاتك.",
    eventsSaveFailed: "ما تم الحفظ. جرّب مرة أخرى.",
    notConfigured: "Telegram bot غير مهيّأ على السيرفر — راجع الـ env vars.",
  },

  articleStats: {
    views: "المشاهدات",
    likes: "الإعجابات",
    dislikes: "عدم الإعجاب",
    comments: "التعليقات",
    questions: "الأسئلة",
    statsTitle: "إحصائيات المقال",
  },

  errors: {
    approveFailed: "ما تمت الموافقة على المقالة. جرّب مرة أخرى.",
    requestFailed: "ما تم إرسال طلب التعديل. جرّب مرة أخرى.",
    errorOccurred: "حدث خطأ",
    somethingWrong: "حدث خطأ. جرّب مرة أخرى.",
  },
} as const;
