import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { db } from "@/lib/db";
import { addCommercialPlanTerm, assignCommercialFeature, deleteCommercialPlan, deleteCommercialPlanTerm, removeCommercialPlanFeature, setCommercialPlanPublished, updateCommercialPlanFeature, updateCommercialPlanTerm } from "../actions";
import { ConfirmDeleteButton } from "../components/confirm-delete-button";
import { DeleteCommercialPlanButton } from "../components/delete-commercial-plan-button";

export default async function CommercialPlanDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [plan, featureLibrary] = await Promise.all([
    db.commercialPlan.findUnique({ where: { id }, include: { prices: { orderBy: { market: "desc" } }, terms: { orderBy: { displayOrder: "asc" } }, features: { include: { feature: true }, orderBy: { displayOrder: "asc" } } } }),
    db.commercialFeature.findMany({ where: { isActive: true }, orderBy: { displayOrder: "asc" } }),
  ]);
  if (!plan) notFound();
  const assignedFeatureIds = new Set(plan.features.map((item) => item.featureId));
  return <main className="mx-auto flex max-w-5xl flex-col gap-6 pb-12" dir="rtl">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">باقات الدفع / إعداد الباقة</p><h1 className="text-2xl font-semibold">{plan.name}</h1><div className="mt-2 flex flex-wrap gap-2 text-sm text-muted-foreground">{plan.prices.map((price) => <span key={price.id} className="rounded-md bg-muted px-2 py-1">{price.market === "SA" ? "السعودية" : "مصر"}: <strong className="text-foreground">{price.monthlyBase} {price.currency}</strong> شهريًا</span>)}</div></div><Badge variant={plan.isPublished ? "default" : "secondary"}>{plan.isPublished ? "منشورة" : "مسودة"}</Badge></header>
    <Card><CardHeader><CardTitle>المدد والهدايا</CardTitle><CardDescription>تكلفة كل سوق = السعر الشهري × الأشهر المدفوعة. الهدية تزيد فترة الخدمة فقط ولا تدخل في الحساب.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Table className="table-fixed"><TableHeader><TableRow><TableHead className="text-right">المدة المدفوعة</TableHead><TableHead className="text-right">الهدية</TableHead><TableHead className="text-right">تكلفة السعودية</TableHead><TableHead className="text-right">تكلفة مصر</TableHead><TableHead className="text-right">إجراءات</TableHead></TableRow></TableHeader><TableBody>{plan.terms.map((term) => { const sa = plan.prices.find((price) => price.market === "SA"); const eg = plan.prices.find((price) => price.market === "EG"); return <TableRow key={term.id}><TableCell className="text-right"><form id={`term-${term.id}`} action={updateCommercialPlanTerm.bind(null, term.id)}><input type="hidden" name="planId" value={plan.id}/><Input className="w-20" name="paidMonths" type="number" min="1" defaultValue={term.paidMonths} required/></form></TableCell><TableCell className="text-right"><Input form={`term-${term.id}`} className="w-20" name="bonusMonths" type="number" min="0" defaultValue={term.bonusServiceMonths} required/></TableCell><TableCell className="text-right font-medium tabular-nums">{sa ? `${sa.monthlyBase * term.paidMonths} ${sa.currency}` : "—"}</TableCell><TableCell className="text-right font-medium tabular-nums">{eg ? `${eg.monthlyBase * term.paidMonths} ${eg.currency}` : "—"}</TableCell><TableCell className="text-right"><div className="flex justify-start gap-2"><Button form={`term-${term.id}`} type="submit" size="sm" variant="outline">حفظ</Button><ConfirmDeleteButton action={deleteCommercialPlanTerm.bind(null, term.id, plan.id)} triggerLabel="حذف" confirmLabel="نعم، احذف المدة" title={`حذف مدة ${term.paidMonths} أشهر؟`} description="سيُحذف السعر المحسوب لهذه المدة من كل الأسواق. لا يمكن التراجع عن هذه العملية." size="sm" /></div></TableCell></TableRow>; })}</TableBody></Table><form action={addCommercialPlanTerm.bind(null,plan.id)} className="grid gap-2 border-t pt-4 md:grid-cols-[1fr_1fr_auto]"><Input name="paidMonths" type="number" min="1" placeholder="الأشهر المدفوعة" required/><Input name="bonusMonths" type="number" min="0" placeholder="أشهر الهدية" required/><Button type="submit">إضافة مدة</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>مزايا الباقة</CardTitle><CardDescription>اختر مزايا من المكتبة، ثم حدّد الكمية أو الملاحظة الخاصة بهذه الباقة.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{plan.features.map((item) => <div key={item.id} className="grid gap-2 rounded-lg border p-3 md:grid-cols-[1.2fr_1fr_1fr_auto_auto]"><div className="self-end"><strong className="text-sm">{item.feature.name}</strong><p className="text-xs text-muted-foreground">{item.feature.unitLabel || "بدون وحدة"}</p></div><form action={updateCommercialPlanFeature.bind(null, item.id, plan.id)} className="contents"><label className="flex flex-col gap-1 text-sm">الكمية<Input name="quantity" type="number" min="0" defaultValue={item.quantity ?? ""}/></label><label className="flex flex-col gap-1 text-sm">ملاحظة<Input name="note" defaultValue={item.note ?? ""}/></label><Button className="self-end" type="submit" variant="outline">حفظ</Button></form><div className="self-end"><ConfirmDeleteButton action={removeCommercialPlanFeature.bind(null, item.id, plan.id)} triggerLabel="إزالة" confirmLabel="نعم، أزل الميزة" title={`إزالة ميزة «${item.feature.name}» من هذه الباقة؟`} description="ستختفي الميزة من هذه الباقة فورًا. يمكنك إعادة إضافتها لاحقًا من قائمة المزايا." /></div></div>)}<form action={assignCommercialFeature.bind(null, plan.id)} className="grid gap-2 border-t pt-4 md:grid-cols-[1.3fr_1fr_1fr_auto]"><select name="featureId" required className="h-10 rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر ميزة من المكتبة</option>{featureLibrary.filter((feature) => !assignedFeatureIds.has(feature.id)).map((feature) => <option key={feature.id} value={feature.id}>{feature.name}</option>)}</select><Input name="quantity" type="number" min="0" placeholder="الكمية (اختياري)"/><Input name="note" placeholder="ملاحظة (اختياري)"/><Button type="submit">إضافة ميزة</Button></form></CardContent></Card>
    <Card><CardHeader><CardTitle>النشر</CardTitle><CardDescription>{plan.isPublished ? "الباقة متاحة لواجهة الدفع عند ربطها بالواجهة لاحقًا." : "المسودة لا تظهر للعميل."}</CardDescription></CardHeader><CardContent><form action={setCommercialPlanPublished.bind(null, plan.id, !plan.isPublished)}><Button type="submit" variant={plan.isPublished ? "outline" : "default"}>{plan.isPublished ? "إيقاف النشر" : "نشر الباقة"}</Button></form></CardContent></Card>
    <Card className="border-destructive/50"><CardHeader><CardTitle>منطقة الخطر</CardTitle><CardDescription>احذف الباقة نهائيًا إذا لن تعود مستخدمة. لإخفائها مؤقتًا استخدم «إيقاف النشر» بدل الحذف.</CardDescription></CardHeader><CardContent><DeleteCommercialPlanButton action={deleteCommercialPlan.bind(null, plan.id)} planName={plan.name}/></CardContent></Card>
  </main>;
}
