import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { UpdateCard } from '@/src/components/updates/UpdateCard';
import { mockClientEvents } from '@/src/events/client-events';
import { colors } from '@/src/theme/tokens';

export function UpdatesRoute({ onOpenArticle }: { onOpenArticle: () => void }) {
  return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><View style={styles.avatar}><Text style={styles.avatarText}>ك</Text></View><View><Text style={styles.kicker}>صباح الخير</Text><Text style={styles.name}>كيما زون</Text></View></View><View style={styles.summary}><View><Text style={styles.summaryNumber}>2</Text><Text style={styles.summaryLabel}>يحتاج قرارك</Text></View><View style={styles.bell}><Ionicons name="notifications-outline" size={22} color={colors.primary} /></View></View><Text style={styles.sectionTitle}>جديد لك اليوم</Text><View style={styles.list}>{mockClientEvents.map((event) => <UpdateCard key={event.id} event={event} onOpen={event.category === 'article-review' ? onOpenArticle : () => undefined} />)}</View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({page:{flex:1,backgroundColor:colors.page},content:{padding:20,paddingBottom:36,gap:16},top:{flexDirection:'row-reverse',justifyContent:'space-between',alignItems:'center',marginTop:10},avatar:{width:42,height:42,borderRadius:14,backgroundColor:colors.navy,alignItems:'center',justifyContent:'center'},avatarText:{color:'#FFF',fontWeight:'800',fontSize:17},kicker:{color:colors.muted,fontSize:13,textAlign:'right'},name:{color:colors.text,fontSize:20,fontWeight:'800',textAlign:'right'},summary:{backgroundColor:'#102531',borderWidth:1,borderColor:'#245564',borderRadius:18,padding:16,flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between'},summaryNumber:{color:colors.primary,fontSize:28,fontWeight:'800',textAlign:'right'},summaryLabel:{color:'#D7F8F8',fontSize:13,textAlign:'right'},bell:{width:42,height:42,borderRadius:14,backgroundColor:'#173745',alignItems:'center',justifyContent:'center'},sectionTitle:{color:colors.text,fontSize:19,fontWeight:'800',textAlign:'right',marginTop:8},list:{gap:11} });
