import { PenLine, Settings, type LucideIcon } from "lucide-react";

import { GoogleIcon } from "@/components/admin/icons/google-icon";
import type { Tier } from "./dashboard-ui";
import { NUM, RAIL } from "./pipeline-row";

/**
 * The dashboard's SEO-health indicator, shared by Articles and Clients so the two
 * sections read as one system and the layout lives in ONE place (Khalid 2026-07-23).
 *
 * It answers the "from outside" question in a glance: what % of entities are a perfect
 * 100 on the shared rubric, and — for the rest — WHICH check blocks them, split by who
 * can act. `content` = the owner's own levers (the editor for articles, the client's
 * data for clients); `system` = auto-generated by our code, so a non-zero system count
 * is a BUG alarm, not a follow-up. The breakdown stays on one scrolling line so the
 * card never grows tall.
 */

export interface SeoCheckTally {
  key: string;
  label: string;
  /** Who can act: content = the owner's lever, system = our code (a bug if > 0). */
  bucket: "content" | "system";
  /** How many entities this check keeps below 100. */
  failing: number;
}

export function SeoHealthCard({
  score,
  perfect,
  below,
  checks,
  contentIcon: ContentIcon = PenLine,
  caption,
  secondary,
}: {
  /** Average SEO score across the entities (0–100) — the headline number and the bar fill. */
  score: number;
  perfect: number;
  below: number;
  checks: SeoCheckTally[];
  /** Marks the owner-fixable group (a pen for articles, a person for clients). */
  contentIcon?: LucideIcon;
  /** Replaces the default "N of M at 100%" text beside the bar (Clients pass drill links). */
  caption?: React.ReactNode;
  /** Optional second metric as its own progress row below SEO (Articles: YMYL risk). */
  secondary?: { label: string; pct: number; tier: Tier; caption?: string };
}) {
  const total = perfect + below;
  if (total === 0) return null;

  const pct = score;
  const tier: Tier = pct >= 80 ? "ok" : pct >= 50 ? "warm" : "hot";
  const contentChecks = checks.filter((c) => c.bucket === "content");
  const systemChecks = checks.filter((c) => c.bucket === "system");

  return (
    <div className="mb-3 rounded-xl border bg-card p-4 shadow-sm">
      {/* Google mark · % · the health bar · caption — all one line. */}
      <div className="flex items-center gap-3">
        <GoogleIcon className="h-7 w-7 shrink-0" />
        <span className={`shrink-0 text-4xl font-extrabold leading-none tabular-nums ${NUM[tier]}`}>
          {pct}%
        </span>
        <div
          className="flex h-2 min-w-[60px] flex-1 overflow-hidden rounded-full bg-red-500/25"
          role="img"
          aria-label={`${pct}% at perfect SEO`}
        >
          <div className="bg-emerald-500" style={{ width: `${pct}%` }} />
        </div>
        {caption ?? (
          <span className="shrink-0 text-[12px] text-muted-foreground">
            {perfect.toLocaleString("en-US")} of {total.toLocaleString("en-US")} at 100%
          </span>
        )}
      </div>

      {/* A second metric as its own progress row, right under SEO (Articles: YMYL risk). */}
      {secondary && (
        <div className="mt-2 flex items-center gap-3 border-t pt-2">
          <span className="shrink-0 text-[10px] font-bold uppercase tracking-wide text-muted-foreground">
            {secondary.label}
          </span>
          <span
            className={`shrink-0 text-2xl font-extrabold leading-none tabular-nums ${NUM[secondary.tier]}`}
          >
            {secondary.pct}%
          </span>
          <div
            className="flex h-2 min-w-[60px] flex-1 overflow-hidden rounded-full bg-muted"
            role="img"
            aria-label={`${secondary.label}: ${secondary.pct}%`}
          >
            <div className={RAIL[secondary.tier]} style={{ width: `${secondary.pct}%` }} />
          </div>
          {secondary.caption && (
            <span className="shrink-0 text-[12px] text-muted-foreground">{secondary.caption}</span>
          )}
        </div>
      )}

      {/* Why not 100% — one scrolling line: content levers (amber) then system alarms (red). */}
      {(contentChecks.length > 0 || systemChecks.length > 0) && (
        <div className="mt-3 flex items-center gap-2 overflow-x-auto border-t pt-3">
          <span className="shrink-0 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">
            Blocking 100%
          </span>
          {contentChecks.length > 0 && (
            <ContentIcon className="h-3.5 w-3.5 shrink-0 text-amber-600 dark:text-amber-400" />
          )}
          {contentChecks.map((c) => (
            <span
              key={c.key}
              className="inline-flex shrink-0 items-center gap-1 rounded-full border border-amber-500/30 bg-amber-500/10 px-2 py-0.5 text-[11px]"
            >
              <span className="font-extrabold tabular-nums text-amber-600 dark:text-amber-400">
                {c.failing}
              </span>
              <span className="text-muted-foreground">{c.label}</span>
            </span>
          ))}
          {systemChecks.length > 0 && (
            <Settings className="h-3.5 w-3.5 shrink-0 text-red-600 dark:text-red-400" />
          )}
          {systemChecks.map((c) => (
            <span
              key={c.key}
              className="inline-flex shrink-0 items-center gap-1 rounded-full border border-red-500/30 bg-red-500/10 px-2 py-0.5 text-[11px]"
            >
              <span className="font-extrabold tabular-nums text-red-600 dark:text-red-400">
                {c.failing}
              </span>
              <span className="text-muted-foreground">{c.label}</span>
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
