export const analytics = {
  title: "تحليلات معمّقة",
  comprehensiveAnalytics:
    "اعرف من زوّارك، متى يتفاعلون، وكيف يقرؤون. القرارات أوضح بمعلومات حقيقية.",
  pageRolePill: "تحقيق عميق — يكمّل لوحة التحكم",

  // Timeframe selector
  timeframeLabel: "الفترة الزمنية",
  timeframe7: "7 أيام",
  timeframe30: "30 يوم",
  timeframe90: "90 يوم",

  // Section titles
  audienceSection: "من هم زوّارك؟",
  audienceSubtitle: "شخصيتهم البصرية وعلاقتهم بمحتواك.",
  behaviorSection: "كيف يتصرّفون؟",
  behaviorSubtitle: "عمق القراءة، الوقت، والتنقّل.",
  timingSection: "متى يتفاعلون؟",
  timingSubtitle: "أنماط النشاط الأسبوعي واليومي.",
  contentSection: "ماذا يضغطون؟",
  contentSubtitle: "الأزرار والروابط الأكثر تفاعلاً.",
  technicalSection: "تجربة الموقع التقنية",
  technicalSubtitle: "Core Web Vitals — مؤشرات أداء جوجل.",
  insightsSection: "ملاحظات قابلة للتنفيذ",
  insightsSubtitle: "نصائح ذكية مبنيّة على بياناتك الفعلية.",

  // Device
  deviceTitle: "الأجهزة",
  deviceMobile: "جوال",
  deviceTablet: "تابلت",
  deviceDesktop: "ديسكتوب",
  deviceUnknown: "غير معروف",

  // New vs returning
  audienceTypeTitle: "زوار جدد مقابل عائدين",
  newVisitors: "زوّار جدد",
  returningVisitors: "زوّار عائدون",
  audienceTypeHint:
    "العائدون = شخص شاهد أكثر من صفحة في نفس الفترة (أكثر التزاماً بمحتواك).",

  // Day of week + hour patterns
  dayOfWeekTitle: "نشاط حسب اليوم",
  dayOfWeekSubtitle: "متى ينشط جمهورك خلال الأسبوع.",
  hourOfDayTitle: "نشاط حسب الساعة",
  hourOfDaySubtitle: "أوقات الذروة خلال اليوم.",
  daySun: "أحد",
  dayMon: "إثنين",
  dayTue: "ثلاثاء",
  dayWed: "أربعاء",
  dayThu: "خميس",
  dayFri: "جمعة",
  daySat: "سبت",

  // Behavior
  bounceRateTitle: "نسبة الارتداد",
  bounceRateHint: "الزوار الذين غادروا فوراً.",
  timeOnPageTitle: "متوسط الوقت في الصفحة",
  scrollDepthTitle: "متوسط عمق التمرير",
  scrollDepthDistTitle: "توزيع عمق القراءة",

  // Generic
  last30d: "آخر 30 يوم",
  last7d: "آخر 7 أيام",
  last90d: "آخر 90 يوم",
  noTraffic: "لا توجد بيانات زيارات بعد. ستتراكم تدريجياً.",
  noAudience: "لا توجد بيانات زوار بعد.",
  noTimingData: "لا توجد بيانات وقت بعد.",
  noInsights: "نحتاج بيانات أكثر لتقديم ملاحظات. تابع نشاطك واطّلع لاحقاً.",

  coreWebVitals: "تجربة الزائر على الموقع",
  performanceMetrics: "متوسط 30 يوم",
  timeOnPage: "وقت الصفحة",
  scrollDepth: "عمق التمرير",
  completionRate: "نسبة الإكمال",
  readingTime: "وقت القراءة",
  conversions: "التحويلات",
  totalConversions: "إجمالي التحويلات",
  conversionTypes: "أنواع التحويلات",
  noConversions: "لا تحويلات بعد",
  campaignPerformance: "أداء الحملات",
  activeCampaigns: "الحملات النشطة",
  impressions: "مرات الظهور",
  clicks: "نقرات",
  views: "مشاهدة",
  users: "مستخدم",
  topClickedLinks: "أكثر الروابط نقرة",
  mostClickedLinks: "في المقالات",
  noLinkClickData: "لا توجد بيانات نقرات بعد.",
  topReferrers: "أهم المصادر",
  noReferrerData: "لا توجد بيانات مصادر بعد.",
  engaged: "تفاعل",
  bounced: "ارتداد",
  lcp: "سرعة ظهور المحتوى",
  cls: "ثبات الصفحة",
  inp: "سرعة الاستجابة",
  ttfb: "سرعة الخادم",
  tbt: "وقت الانشغال",
  sAvg: "ث متوسط",
  percentAvg: "% متوسط",
  topCtaClicks: "أكثر الأزرار نقرة",
  ctaClicksDesc: "الأزرار والروابط المتتبعة",
  noCtaData: "لا توجد بيانات نقرات بعد.",
  ctaTypeButton: "زر",
  ctaTypeLink: "رابط",
  ctaTypeForm: "نموذج",
  ctaTypeBanner: "لافتة",
  ctaTypePopup: "نافذة منبثقة",

  // Legacy — kept for backward compat with other pages
  views7d: "مشاهدات (7 أيام)",
  views30d: "مشاهدات (30 يوماً)",
  totalPageViews: "إجمالي المشاهدات",
  articles: "المقالات",
  client: "العميل",
  engagementRate: "نسبة التفاعل",
  conversionRate: "نسبة التحويل",
  trafficSources: "مصادر الزيارات",
  engagementMetrics: "التفاعل",
  userBehavior: "سلوك المستخدم",
  topPerformingArticles: "أفضل المقالات",
  articlesRankedByViews: "حسب المشاهدات (30 يوماً)",
  scroll: "تمرير",
  noArticles: "لا توجد مقالات بعد.",
  clientPageViews: "مشاهدات صفحة العميل",
  brandPageAnalytics: "صفحة العلامة والملف (30 يوماً)",
  totalClientViews: "إجمالي المشاهدات",
  uniqueVisitors: "زوار فريدون",
  scrollDepthDist: "توزيع عمق التمرير",
  sourceOrganic: "بحث جوجل",
  sourceDirect: "زيارة مباشرة",
  sourceReferral: "إحالة من موقع آخر",
  sourceSocial: "شبكات اجتماعية",
  sourcePaid: "إعلان مدفوع",
  sourceUnknown: "غير معروف",
} as const;
