export const articles = {
  manageApproveArticles: "إدارة المقالات والموافقة عليها",
  pendingApprovalTab: "بانتظار الموافقة",
  scheduledTab: "مجدولة",
  published: "منشور",
  allArticles: "كل المقالات",
  noPending: "لا توجد مقالات بانتظار الموافقة. سنخبرك عند وصول مقالة جديدة.",
  noScheduled: "لا توجد مقالات مجدولة. ستظهر هنا بعد موافقتك — جاهزة للنشر من قِبل المحرر.",
  noPublished: "لا توجد مقالات منشورة بعد.",
  noOnSite: "ما فيه مقال منشور على موقعك بعد. أول ما توافق على مقال وننشره، يظهر هنا.",
  noArticlesYet: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
  scheduledFor: "موعد النشر",
  awaitingPublish: "بانتظار النشر من المحرر",
  scheduledHint: "وافقتَ على المقالة — المحرر سيختار موعد النشر قريباً.",
  created: "تاريخ الإنشاء",
  pendingApprovalStatus: "بانتظار الموافقة",
  statusPublished: "منشور",
  statusDraft: "مسودة",
  statusScheduled: "مجدول",
  statusWriting: "قيد الكتابة",
  statusArchived: "مؤرشف",
  words: "كلمة",
  minRead: "دقيقة قراءة",
  tag: "وسم",
  tags: "وسوم",
  preview: "معاينة",
  approve: "موافقة",
  requestChanges: "طلب تعديلات",
  approving: "جاري الموافقة…",
  approveArticle: "الموافقة على المقالة",
  backToArticles: "العودة للمقالات",
  approveConfirm: "تأكيد الموافقة على المقالة؟ المحرر سيقوم بنشرها بعد الموافقة.",
  approveSuccess: "تمت الموافقة — المحرر سيقوم بالنشر قريباً",
  approveFailed: "ما تمت الموافقة على المقالة. جرّب مرة أخرى.",
  requestSuccess: "تم إرسال طلب التعديلات للمحرر",
  requestFailed: "ما تم إرسال طلب التعديل. جرّب مرة أخرى.",
  errorOccurred: "حدث خطأ",
  confirmYes: "نعم، وافق",
  basicContent: "المحتوى الأساسي",
  titleSlugExcerpt: "العنوان والرابط والملخص والبيانات",
  title: "العنوان",
  slug: "الرابط",
  excerpt: "الملخص",
  status: "الحالة",
  datePublished: "تاريخ النشر",
  inLanguage: "اللغة",
  articleContent: "محتوى المقالة",
  fullArticleBody: "نص المقالة كاملاً",
  format: "التنسيق",
  formatLabel: "التنسيق",
  wordsCount: "كلمة",
  wordCount: "عدد الكلمات",
  readingTime: "وقت القراءة",
  contentDepth: "عمق المحتوى",
  characters: "حرف",
  credentials: "المؤهلات",
  relationships: "العلاقات",
  clientCategoryAuthor: "العميل والتصنيف والكاتب والوسوم",
  client: "العميل",
  category: "التصنيف",
  author: "الكاتب",
  featuredImage: "الصورة الرئيسية",
  mainArticleImage: "صورة المقالة الرئيسية",
  noImage: "لا توجد صورة",
  altText: "النص البديل",
  caption: "التسمية التوضيحية",
  imageGallery: "معرض الصور",
  imagesCount: "صورة",
  galleryImage: "صورة المعرض",
  min: "دقيقة",
  seoMeta: "بيانات البحث",
  searchEngineOpt: "تحسين محركات البحث",
  seoTitle: "عنوان البحث",
  seoTitleLabel: "عنوان البحث",
  seoDescription: "وصف البحث",
  seoDescriptionLabel: "وصف البحث",
  metaRobots: "إعدادات الروبوتات",
  canonicalUrl: "الرابط الأساسي",
  openGraph: "مشاركة الشبكات",
  ogType: "نوع المشاركة",
  ogArticleAuthor: "كاتب المقالة",
  ogImage: "صورة المشاركة",
  ogPublishedTime: "وقت النشر للمشاركة",
  twitterCards: "بطاقات تويتر",
  twitterCard: "بطاقة تويتر",
  twitterCardType: "نوع بطاقة تويتر",
  twitterSite: "حساب تويتر",
  twitterCreator: "المنشئ",
  faqs: "الأسئلة الشائعة",
  questionsCount: "سؤال",
  relatedArticles: "مقالات ذات صلة",
  technicalSeo: "بيانات تقنية للبحث",
  sitemapSettings: "خريطة الموقع والإعدادات التقنية",
  sitemapPriority: "أهمية الصفحة في البحث",
  sitemapChangeFreq: "تكرار التحديث",
  breadcrumbPath: "مسار التصفح",
  jsonld: "بيانات البحث المنظمة",
  schemaOrg: "بيانات منظمة لجوجل",
  lastGenerated: "آخر تحديث",
  citations: "المراجع",
  sourcesCount: "مصدر",
  requestChangesTitle: "طلب تعديلات",
  feedbackLabel: "ملاحظاتك أو التعديلات المطلوبة",
  feedbackPlaceholder: "صف التعديلات التي تود رؤيتها...",
  feedbackSent: "سنرسل ملاحظاتك لفريق المحتوى.",
  cancel: "إلغاء",
  sendFeedback: "إرسال الملاحظات",
  sending: "جاري الإرسال…",
  pleaseProvideFeedback: "أضف ملاحظاتك",
  articleLabel: "المقالة:",
  publishedOn: "نُشر في",
  articlePreviewTitle: "معاينة المقالة",
  reviewBeforeApproval: "تفقد المقالة قبل الموافقة",
  socialSharing: "مشاركة على الشبكات الاجتماعية",
  twitterSharingDesc: "بيانات مشاركة تويتر",
  articlesCount: "مقالة",
} as const;
