export const bookings = {
  title: "الحجوزات",
  subtitle: "كل طلبات الحجز اللي وصلتك من زرّ «احجز الآن» — تابعها وغيّر حالتها.",
  pageHint:
    "لما زائر يعبّي فورم الحجز في مقالك أو صفحتك، يوصلك هنا فوراً (وعلى تيليجرام لو مربوط). كلّم العميل، وعلّم الحالة عشان ما يضيع أحد.",
  new: "جديد",
  contacted: "تواصلت",
  done: "تم",
  archived: "مؤرشف",
  total: "الكل",
  newHint: "وصل ولسّا ما تواصلت",
  contactedHint: "تواصلت معه",
  doneHint: "خلّصت الحجز",
  archivedHint: "مؤرشف",
  totalHint: "كل الطلبات",
  searchPlaceholder: "ابحث بالاسم أو الجوال أو الرسالة…",
  all: "الكل",
  selected: "محدد",
  bulkContacted: "علّم: تواصلت",
  bulkArchive: "أرشفة",
  bulkDelete: "حذف",
  clearSelection: "إلغاء التحديد",
  selectAll: "تحديد الكل",
  showing: "عرض",
  of: "من",
  restoreNew: "رجّعه جديد",
  markContacted: "تواصلت",
  markDone: "تم",
  markArchived: "أرشفة",
  delete: "حذف",
  noBookings: "ما في حجوزات بعد",
  emptyHint: "أول ما يوصلك طلب حجز، بيظهر هنا.",
  noMatchSearch: "ما في نتائج للبحث.",
  noBookingsFiltered: "ما في حجوزات بهذي الحالة.",
  details: "تفاصيل الحجز",
  contactSection: "التواصل",
  phone: "الجوال",
  email: "البريد",
  whatsappBtn: "واتساب",
  callBtn: "اتصال",
  mailBtn: "إيميل",
  preferredAt: "الموعد المفضّل",
  noPreferred: "ما حدّد موعد",
  messageLabel: "الرسالة",
  noMessage: "بدون رسالة",
  sourceLabel: "المصدر",
  articleLabel: "المقال",
  timeline: "التفاصيل الزمنية",
  createdAt: "وصل في",
  ipAddress: "IP",
  userAgent: "المتصفح",
  confirm: "تأكيد",
  cancel: "إلغاء",
  updateSuccess: "تم تحديث الحالة",
  updateFailed: "تعذّر تحديث الحالة",
  deleteConfirm: "متأكد تبغى تحذف هذا الطلب؟",
  deleteSuccess: "تم الحذف",
  deleteFailed: "تعذّر الحذف",
  bulkUpdateSuccess: "تم تحديث الطلبات المحددة",
  bulkDeleteConfirm: "متأكد تبغى تحذف الطلبات المحددة؟",
  bulkDeleteSuccess: "تم حذف الطلبات المحددة",
  statusBadge: { new: "جديد", contacted: "تواصلت", done: "تم", archived: "مؤرشف" },
  sourceMap: {
    article_dock: "من المقال (الجوال)",
    article_card: "من كارت العميل",
    client_page: "من صفحة نشاطك",
    client_list: "من قائمة الأنشطة",
  },
  // Channel (form callback vs tracked WhatsApp click)
  channelAll: "كل القنوات",
  channelForm: "اترك رقمك",
  channelWhatsapp: "واتساب",
  whatsapp: "تواصل واتساب",
  whatsappHint: "ضغطوا واتساب ووصلتك رسالتهم",
  whatsappLead: "زائر تواصل عبر واتساب",
  whatsappLeadNote:
    "هذا الزائر ضغط زرّ واتساب ووصلته رسالة جاهزة تعرّفك إنه جاي من مدوّنتي. رقمه وحديثه معك على واتساب مباشرة — احنا ما نحفظ رقمه، بس نثبّت لك إنه تواصل.",
  anonymousName: "زائر واتساب",
  geoLabel: "الموقع التقريبي",
  unknownGeo: "غير معروف",
  // Confirmed appointment (provider sets it from here)
  confirmedAt: "الموعد المؤكَّد",
  noConfirmed: "لسّا ما أكّدت موعد",
  setConfirmed: "أكّد موعداً",
  saveConfirmed: "حفظ الموعد",
  clearConfirmed: "إلغاء الموعد",
  confirmedSaved: "تم تأكيد الموعد",
  confirmedCleared: "تم إلغاء الموعد المؤكَّد",
  confirmedFailed: "تعذّر حفظ الموعد",
  confirmedBadge: "موعد مؤكَّد",
} as const;
