export const dashboard = {
  welcome: "هذي نظرتك السريعة على آخر 30 يوم — تابع وافتح أي قسم لمزيد من التفاصيل.",
  greetingFor: "مرحباً، {name}",

  // This-month summary
  thisMonth: "هذا الشهر",
  thisMonthArticles: "{n} مقال نُشر",
  thisMonthViews: "{n} مشاهدة",
  thisMonthSubscribers: "{n} مشترك جديد",

  // Section titles
  actionItemsTitle: "يحتاج انتباهك",
  actionItemsSubtitle: "أمور بانتظار قرارك أو متابعتك.",
  periodDays: "{n} يوماً",
  periodDaysFew: "{n} أيام",
  periodAria: "فترة الأرقام",
  attentionArticles: "{n} مقال بانتظار موافقتك",
  attentionComments: "{n} تعليق بانتظار مراجعتك",
  attentionSupport: "{n} رسالة دعم جديدة",
  attentionClear: "ما في شي بانتظارك الآن",
  siteViews: "مشاهدات على مدونتي",
  siteViewsHint: "قراءات مقالاتك وزيارات صفحتك",
  contactsTitle: "تواصل معك",
  contactsHint: "حجوزات ورسائل من زوّارك",
  overviewSubtitle: "من بحث جوجل (Search Console) ومن مدونتي · آخر {days}",
  moreInAnalytics: "تفاصيل أكثر في التحليلات",
  googleTitle: "أداؤك في جوجل",
  googleSubtitle: "صفحتك ومقالاتك على مدونتي في بحث جوجل — من Search Console مباشرةً · آخر {days} يوماً ({range}) · النِّسب مقارنةً بالـ{days} يوماً السابقة",
  googleImpressions: "ظهورك في جوجل",
  googleImpressionsHint: "مرّات ظهور صفحاتك في نتائج البحث",
  googleClicks: "زيارات من جوجل",
  googleClicksHint: "نقرات من نتائج البحث إلى صفحاتك",
  googleCtr: "نسبة النقر",
  googleCtrHint: "من كل ١٠٠ ظهور، كم واحد ضغط",
  googlePosition: "متوسط ترتيبك",
  googlePositionHint: "كل ما قلّ الرقم كنت أعلى في النتائج",
  googleTopQueries: "كلمات البحث اللي طلّعتك",
  googleReportButton: "تأكّد من أرقامك في تقرير جوجل",
  googleEmpty: "لسّا ما ظهرت صفحاتك في جوجل خلال آخر {days} يوماً — بيانات جوجل تبدأ بعد أيام من نشر المقال.",
  googleUnavailable: "تعذّر الوصول لبيانات جوجل الآن — جرّب بعد قليل.",
  performanceTitle: "الأداء",
  performanceSubtitle: "مؤشّرات وصول محتواك ونشاط زوّارك.",
  audienceTitle: "الجمهور",
  audienceSubtitle: "نمو متابعيك وعمق تفاعلهم.",

  // Trends
  trendUp: "↗",
  trendDown: "↘",
  trendFlat: "→",
  vsLastWeek: "مقارنة بالأسبوع السابق",
  vsLastMonth: "مقارنة بالشهر السابق",
  noPrevData: "لا توجد بيانات سابقة للمقارنة بعد.",

  // Engagement benchmarks
  benchmarkExcellent: "ممتاز",
  benchmarkGood: "جيد",
  benchmarkAverage: "متوسط",
  benchmarkLow: "يحتاج تحسين",

  // Avg time formatting
  avgTimeMinutes: "{n} دقيقة",
  avgTimeManyMinutes: "أكثر من {n} دقيقة",

  subscription: "الاشتراك",
  currentPlan: "الباقة الحالية",
  subStatusActive: "نشط",
  subStatusInactive: "غير نشط",
  subStatusExpired: "منتهي",
  subStatusCancelled: "ملغي",
  perYear: "سنوياً",
  currencySar: "ريال سعودي",
  content: "المحتوى",
  articlesThisMonth: "المقالات هذا الشهر",
  subscribers: "المشتركون",
  newsletterList: "قائمة النشرة",
  totalSubscribers: "إجمالي المشتركين",
  articles: "المقالات",
  manageApprove: "المقالات والموافقات",
  pendingApproval: "بانتظار الموافقة",
  allApproved: "تمت الموافقة على الكل",
  viewContent: "عرض المحتوى",
  analytics: "الإحصائيات",
  viewsEngagement: "المشاهدات والتفاعل",
  viewAnalytics: "عرض الإحصائيات",
  comments: "التعليقات",
  pendingReview: "بانتظار المراجعة",
  allReviewed: "تمت مراجعة الكل",
  moderateComments: "مراجعة التعليقات",
  media: "الوسائط",
  assetsBranding: "الملفات والهوية",
  manageLibrary: "إدارة المكتبة",
  viewMedia: "عرض الوسائط",
  support: "الدعم",
  viewMessages: "عرض الرسائل",
  newSupportMessages: "{n} رسالة جديدة",
  noNewSupportMessages: "لا رسائل جديدة",
  manageSupport: "إدارة الدعم",
  engagementScore: "درجة التفاعل",
  activeUsers: "المستخدمون النشطون",
  avgTime: "متوسط الوقت",
  scroll: "التمرير",
  returnRate: "معدل الزوار العائدين",
  days7: "آخر 7 أيام",
  days30: "آخر 30 يوم",
  interactions: "التفاعلات",
  conversions: "التحويلات",
  likes: "إعجابات",
  shares: "مشاركات",
  commentsLabel: "تعليقات",
  rate: "النسبة",
  bounce: "نسبة الارتداد",
  topPerforming: "أفضل المقالات أداءً",
  byViewsEngagement: "حسب المشاهدات والتفاعل والتحويلات",
  byViews: "حسب المشاهدات",
  byEngagement: "حسب التفاعل",
  views: "مشاهدة",
  score: "الدرجة",
  trafficSources: "مصادر الزيارات",
  last30Days: "آخر 30 يوم",
  recentActivity: "النشاط الأخير",
  latestUpdates: "آخر التحديثات والأحداث",
  noArticles: "لا توجد مقالات بعد. ستظهر هنا عند إضافتها من فريق مودونتي.",
  noTraffic: "لا توجد بيانات زيارات بعد. ستتراكم خلال أيام من نشر المقالات.",
  noActivity: "لا يوجد نشاط حديث.",
  newArticlePublished: "مقالة جديدة نُشرت",
  newComment: "تعليق جديد",
  newSubscriber: "مشترك جديد",
  onArticle: "على المقالة",
  unknown: "غير معروف",
} as const;
