export const login = {
  clientPortal: "بوابة العملاء",
  signInCopy: "سجّل الدخول للوصول إلى لوحة التحكم والمحتوى والإحصائيات.",
  yourDashboard: "لوحتك",
  trackEverything: "تابع كل شيء",
  secureLogin: "تسجيل آمن",
  safeAccountAccess: "دخول آمن لحسابك",
  accountSecurity: "أمان الحساب",
  protectedData: "بياناتك محمية",
  realtimeUpdates: "تحديثات فورية",
  stayInformed: "ابقَ على اطلاع",
  secureAccess: "وصول آمن للعملاء.",
  referTitle: "أدخل زميلاً واحصل على 5 مقالات مجانية",
  referDesc: "عند اشتراك من أدخلته، ستحصل على 5 مقالات مجانية.",
  signIn: "تسجيل الدخول",
  signingIn: "جاري تسجيل الدخول…",
  useEmailOrSlug: "استخدم بريدك أو معرف العميل وكلمة المرور للدخول.",
  emailOrSlug: "البريد أو معرف العميل",
  placeholderIdentifier: "example@mail.com أو معرف-العميل",
  password: "كلمة المرور",
  showPassword: "إظهار كلمة المرور",
  hidePassword: "إخفاء كلمة المرور",
  invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
  somethingWrong: "حدث خطأ. جرّب مرة أخرى.",
} as const;
