export const nav = {
  dashboard: "لوحة التحكم",
  seo: "معلومات نشاطك",
  articles: "المقالات",
  siteArticles: "مقالاتك على موقعك",
  siteArticlesEnabledHint: "نشر مقالاتك على موقعك مفعّل",
  media: "الصور والملفات",
  analytics: "الإحصائيات",
  campaigns: "الحملات",
  comments: "التعليقات",
  questions: "أسئلة الزوار",
  // «الأسئلة الشائعة» وحدها كانت تُخلَط بـ«أسئلة صفحتك»: الأولى أسئلة تحت المقالات
  // (جدول `articleFAQ`)، والثانية أسئلة صفحة الموقع (`clientFAQ`). الاسم يذكر نطاقه.
  faqs: "أسئلة مقالاتك",
  clientComments: "آراء حول نشاطك",
  clientReviews: "تقييمات نشاطك",
  pageContent: "محتوى الموقع",
  gallery: "معرض الصور",
  reels: "الريلز",
  videos: "الفيديوهات",
  pageFaq: "أسئلة صفحتك",
  siteHealth: "صحة موقعك",
  subscribers: "مشتركو النشرة",
  leads: "العملاء المحتملون",
  mySite: "تصميم الموقع",
  profile: "بيانات نشاطك",
  documents: "وثائقك",
  settings: "الإعدادات",
  invoices: "الفواتير",
  support: "الدعم",
  bookings: "الحجوزات",
  signOut: "تسجيل الخروج",
  expandSidebar: "توسيع القائمة",
  collapseSidebar: "طي القائمة",
  // Group headings for the sidebar — twenty items in one column read as a wall.
  groupSite: "موقعك",
  groupBusiness: "نشاطك",
  groupMedia: "الوسائط",
  groupAudience: "جمهورك",
  groupAccount: "حسابك",
} as const;
