export const profile = {
  title: "معلومات النشاط",
  description: "تعديل بيانات النشاط والتواصل",
  basicInfo: "البيانات الأساسية",
  name: "اسم النشاط",
  legalName: "الاسم القانوني",
  alternateName: "الاسم البديل",
  url: "الموقع الإلكتروني",
  slogan: "الشعار",
  organizationDescription: "وصف النشاط",
  contactInfo: "معلومات التواصل",
  contactType: "نوع جهة الاتصال",
  address: "العنوان",
  addressStreet: "الشارع",
  addressCity: "المدينة",
  addressCountry: "الدولة",
  addressPostalCode: "الرمز البريدي",
  addressRegion: "المنطقة",
  addressNeighborhood: "الحي",
  addressBuildingNumber: "رقم المبنى",
  addressAdditionalNumber: "الرقم الإضافي (العنوان الوطني)",
  addressAdditionalNumberHint: "4 أرقام تُكمّل رقم المبنى لتحديد الموقع بدقّة",
  saudiGulf: "السجل التجاري والضرائب",
  commercialRegistrationNumber: "رقم السجل التجاري",
  vatID: "رقم ضريبة القيمة المضافة (VAT)",
  vatIDHint: "15 رقم يبدأ وينتهي بـ 3",
  taxID: "الرقم المميز / المعرّف الضريبي (TIN)",
  taxNumber: "الرقم الضريبي",
  legalForm: "الشكل القانوني",
  business: "معلومات الأعمال",
  industry: "القطاع",
  targetAudience: "الجمهور المستهدف",
  organizationType: "نوع المنظمة",
  foundingDate: "تاريخ التأسيس",
  businessBrief: "نبذة عن الأعمال",
  socialProfiles: "الحسابات الاجتماعية",
  socialProfilesHint: "رابط واحد في كل سطر (لينكدإن، تويتر، فيسبوك)",
  seo: "بيانات البحث",
  seoTitle: "عنوان البحث",
  seoDescription: "وصف البحث",
  canonicalUrl: "الرابط الأساسي",
  canonicalUrlHint: "إذا نُسخت مقالتك في مكان آخر، هذا الرابط يخبر جوجل بالمصدر الأصلي.",
  twitter: "تويتر",
  twitterTitle: "عنوان تويتر",
  twitterDescription: "وصف تويتر",
  twitterSite: "@اسم_المستخدم",
  seoSettings: "إعدادات البحث",
  technicalProfile: "الملف التقني",
  platform: "المنصة",
  stagingUrl: "رابط الموقع التجريبي",
  seoGoals: "أهداف الظهور في البحث",
  primaryGoal: "الهدف الرئيسي",
  kpis: "مؤشرات النجاح (مثل: عدد الزوار، المبيعات)",
  goalsDisclaimer: "نساعدك نحدد الأولويات ونرتب الخطة. النتائج تتحقق تدريجياً وتتأثر بالمنافسة وجودة الموقع والاستمرارية — نعمل معك لأفضل نتيجة ممكنة دون وعد بأرقام أو مواعيد ثابتة.",
  successMetrics: "معايير النجاح",
  timeline: "الجدول الزمني",
  seoMetrics: "مقاييس البحث",
  domainAuthority: "قوة الموقع في البحث",
  backlinkCount: "عدد الروابط الخلفية",
  linkBuildingPolicy: "سياسة بناء الروابط",
  brandGuidelines: "إرشادات البراند",
  contentTone: "نبرة المحتوى",
  complianceConstraints: "قيود الامتثال",
  complianceIndustry: "قطاع الامتثال",
  restrictedClaims: "ادعاءات مقيدة",
  googleBusinessProfileUrl: "رابط ملف نشاطك التجاري على جوجل",
  forbiddenKeywords: "كلمات ممنوعة",
  forbiddenClaims: "ادعاءات ممنوعة",
  competitiveMentionsAllowed: "السماح بذكر المنافسين",
} as const;
