export const seo = {
  title: "معلومات مهمة",
  heroDescription:
    "«مدونتي» هي منصة تمكّن أصحاب الأعمال من الحصول على مقالات جاهزة ومتجددة ترفع ظهورهم على محركات البحث. ببساطة، هي تساعدك على نشر محتوى مدروس باستمرار دون الحاجة لأن تكتب بنفسك، مما يوفر لك الوقت ويعزز ظهور علامتك.",
  intake: "معلومات مهمة",
  competitors: "المنافسون",
  keywords: "الكلمات المفتاحية",
  project: "المشروع",
  addCompetitor: "إضافة منافس",
  addKeyword: "إضافة كلمة",
  name: "الاسم",
  url: "الرابط",
  notes: "ملاحظات",
  keyword: "الكلمة",
  intent: "النية",
  priority: "الأولوية",
  reason: "السبب",
  edit: "تعديل",
  delete: "حذف",
  save: "حفظ",
  cancel: "إلغاء",
  saveIntake: "حفظ الاستمارة",
  transactional: "معاملاتي",
  informational: "معلوماتي",
  commercial: "تجاري",
  goals: "الأهداف",
  budget: "الميزانية",
  contactPerson: "مَن نتواصل معه؟",
  reportingPreference: "شكل التقارير",
  weekly: "أسبوعي",
  monthly: "شهري",
  noCompetitors: "لا يوجد منافسون بعد.",
  noKeywords: "لا توجد كلمات مفتاحية بعد.",
  deleteConfirm: "تأكيد الحذف؟",
  keywordsTabNote: "أضف الكلمات المستهدفة من تبويب «الكلمات المفتاحية» أعلى الصفحة.",
} as const;
