export const support = {
  title: "رسائل الدعم",
  manageContact: "كل رسائل التواصل من الزوار، مع إمكانية الرد بالإيميل وحفظ الردود.",
  pageHint:
    "هذي الرسائل وصلتك من نموذج «تواصل معنا» في الموقع. كل رسالة فيها بيانات المرسل والموضوع، وتقدر ترد عليه مباشرة من هنا — الرد ينحفظ ويرسل بريد للزائر.",
  all: "الكل",
  new: "جديد",
  archived: "مؤرشف",
  unreadMessages: "ما تم فتحها بعد",
  read: "مقروء",
  messagesRead: "تم الاطلاع عليها",
  replied: "تم الرد",
  messagesReplied: "أرسلت لها رد",
  total: "الإجمالي",
  allMessages: "كل الرسائل",
  archivedHint: "خارج صندوق الوارد",
  messages: "الرسائل",
  messageDetails: "تفاصيل الرسالة",
  selectToView: "اختر رسالة لعرض تفاصيلها",
  noMessagesFound: "لا توجد رسائل بعد.",
  noMatchSearch: "ما لقيت رسائل تطابق بحثك.",
  searchPlaceholder: "ابحث في الاسم، الإيميل، الموضوع، أو نص الرسالة…",
  showing: "إظهار",
  of: "من",
  from: "من",
  subject: "الموضوع",
  received: "تاريخ الاستلام",
  message: "الرسالة",
  referrer: "صفحة الإحالة",
  markRead: "مقروء",
  markReplied: "تم الرد",
  markArchived: "أرشفة",
  markNew: "إعادة لـ«جديد»",
  delete: "حذف",
  deleteConfirm: "تأكيد حذف هذه الرسالة؟",
  bulkDeleteConfirm: "تأكيد حذف الرسائل المحددة؟",
  updateFailed: "ما تم تحديث الرسالة. جرّب مرة أخرى.",
  updateSuccess: "تم تحديث حالة الرسالة.",
  deleteFailed: "ما تم حذف الرسالة. جرّب مرة أخرى.",
  deleteSuccess: "تم حذف الرسالة.",
  bulkUpdateSuccess: "تم تحديث الرسائل المحددة.",
  bulkDeleteSuccess: "تم حذف الرسائل المحددة.",
  selected: "محدّدة",
  selectAll: "تحديد الكل",
  clearSelection: "إلغاء التحديد",
  bulkActions: "إجراءات",
  bulkMarkRead: "تعليم كمقروءة",
  bulkArchive: "أرشفة",
  bulkDelete: "حذف",
  reply: "ردّك على الزائر",
  replyPlaceholder: "اكتب ردّك هنا…",
  yourReply: "ردك",
  sendReply: "إرسال الرد",
  replyViaEmail: "إرسال الرد عبر البريد للزائر",
  replySuccess: "تم إرسال الرد بنجاح.",
  replyFailed: "ما تم إرسال الرد. جرّب مرة أخرى.",
  replySavedEmailFailed: "تم حفظ الرد، لكن ما تم إرسال البريد.",
  metaSection: "تفاصيل الإرسال",
  ipAddress: "عنوان IP",
  userAgent: "المتصفح",
  sentAt: "وصلت",
  readAt: "فُتحت",
  repliedAt: "أُجيب عليها",
  statusBadge: {
    new: "جديد",
    read: "مقروء",
    replied: "تم الرد",
    archived: "مؤرشف",
  },
} as const;
