export const telegram = {
  cardTitle: "Telegram",
  cardHint: "استلم إشعارات engagement على تيليجرام مباشرة.",
  statusConnected: "مربوط",
  statusDisconnected: "غير مربوط",
  connectedSince: "تم الربط في",
  connect: "ربط حساب Telegram",
  disconnect: "فصل الربط",
  disconnectConfirm: "تأكيد فصل الربط؟ راح تتوقف الإشعارات.",
  disconnected: "تم فصل الربط.",
  sendTest: "إرسال رسالة اختبار",
  testSent: "تم إرسال الاختبار.",
  testFailed: "فشل إرسال الاختبار.",
  pairingTitle: "خطوات الربط",
  pairingStep1: "افتح الرابط:",
  pairingStep2: "اكتب /start في المحادثة",
  pairingStep3: "ارجع هنا، الكود تحت — أرسله للبوت في تيليجرام",
  pairingCode: "كود الربط",
  pairingExpires: "صالح حتى",
  generateCode: "توليد كود ربط",
  codeCopied: "تم نسخ الكود.",
  codeGenerated: "تم توليد الكود — أرسله للبوت في تيليجرام.",
  eventsTitle: "الإشعارات اللي تبغاها",
  eventsHint: "اختر بس الأحداث المهمة عشان ما تتزحم رسائلك.",
  eventsPickBeforePair:
    "تقدر تختار تفضيلاتك من الآن — لما تربط حسابك في تيليجرام، التفضيلات بتصير شغّالة فوراً.",
  selectAll: "تحديد الكل",
  selectNone: "إلغاء الكل",
  eventsSaved: "تم حفظ تفضيلاتك.",
  eventsSaveFailed: "ما تم الحفظ. جرّب مرة أخرى.",
  notConfigured: "Telegram bot غير مهيّأ على السيرفر — راجع الـ env vars.",
} as const;
