/**
 * Client Form Configuration
 * Defines all form sections and fields programmatically
 * Updated for tab-based layout
 */

export interface FormSectionConfig {
  id: string;
  title: string;
  description: string;
  icon: string;
  fields: string[];
  required: string[];
  priority: "primary" | "secondary";
  availableInCreate: boolean;
  availableInEdit: boolean;
}

/**
 * Field visibility metadata
 * Defines which fields should be excluded from count or are conditionally rendered
 */
const fieldVisibilityRules = {
  // Auto-generated/auto-calculated fields: show but don't count
  autoGenerated: [] as readonly string[],
  // Edit-only fields: only count in edit mode
  editOnly: ["subscriptionStatus", "paymentStatus"] as readonly string[],
} as const;

export const clientFormSections: FormSectionConfig[] = [
  {
    id: "required",
    title: "Information",
    description: "Key client information needed to create the account",
    icon: "User",
    // Admin-owned fields that the grouped-update writers actually persist live in
    // their own groups below (contact/address/legal). Fields kept here are either
    // written by updateRequiredFields (name/slug/email) OR are
    // console-owned and intentionally NOT mutated by the admin grouped save
    // (legalName, foundingDate, slogan, businessBrief, address details, vatID, …) — they stay
    // listed so the form still carries their values, but no admin writer touches them.
    fields: [
      "name",
      "slug",
      "alternateName",
      "email",
      "legalName",
      "foundingDate",
      "slogan",
      "numberOfEmployees",
      "commercialRegistrationNumber",
      "businessBrief",
      // (formerly: licenseNumber, licenseAuthority — moved to Client.ymylData JSON via YMYL section)
      "addressStreet",
      "addressNeighborhood",
      "addressBuildingNumber",
      "addressAdditionalNumber",
      "addressCity",
      "addressRegion",
      "addressPostalCode",
      "addressLatitude",
      "addressLongitude",
      "vatID",
      "organizationType",
    ],
    required: ["name", "slug", "email"],
    priority: "primary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "subscription",
    title: "Subscription",
    description: "Subscription tier",
    icon: "CreditCard",
    // subscriptionStatus + paymentStatus removed (2026-06-10): owned by the Activate/Suspend
    // sidebar pages. subscriptionStartDate + subscriptionEndDate + articlesPerMonth removed
    // (2026-06-10): dates come from the invoice workflow (Accounts → createInvoiceAction),
    // and articlesPerMonth is derived from the tier config — neither is edited in this form.
    fields: [
      "subscriptionTier",
      "subscriptionTierConfigId",
    ],
    required: ["subscriptionTier"],
    priority: "primary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "business",
    title: "Content priorities",
    description: "SEO keyword priorities (audience/strategy moved to client intake)",
    icon: "Building2",
    fields: ["contentPriorities", "industryId"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "contact",
    title: "Contact",
    description: "Contact information (moved into Information tab)",
    icon: "Mail",
    // Admin-owned. Routed here so updateContactFields() actually persists them
    // (it selects + writes exactly these 4, with sameAs URL normalization).
    fields: ["url", "phone", "contactType", "sameAs"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "address",
    title: "Address",
    description: "Complete address details for local SEO",
    icon: "MapPin",
    // Only addressCountry is admin-owned (drives the console's isSaudi tax/address logic).
    // The rest of the address is console-owned, so it is NOT listed here — updateAddressFields()
    // only diffs the fields in this list, leaving the console-entered address untouched.
    fields: ["addressCountry"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "legal",
    title: "Legal",
    description: "Legal information and compliance details (moved into Information tab)",
    icon: "FileText",
    // Only legalForm is admin-owned. vatID/taxID/CR are console-owned (country-aware tax),
    // so they are NOT listed — updateLegalFields() only diffs legalForm, leaving the rest intact.
    fields: ["legalForm"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "seo",
    title: "SEO",
    description: "SEO metadata and meta tags",
    icon: "Search",
    // description (client-owned via console) + canonicalUrl (auto-derived) + keywords (Google ignores meta keywords; JSON-LD falls back to contentPriorities) removed 2026-06-10.
    fields: ["seoTitle", "seoDescription", "organizationType", "parentOrganizationId", "businessActivityCode", "isicV4", "gbpProfileUrl", "gbpPlaceId", "gbpAccountId", "gbpLocationId", "gbpCategory", "priceRange"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "media-social",
    title: "Media",
    description: "Logo, OG image, Twitter image, and Twitter card settings",
    icon: "Image",
    fields: ["logoMediaId", "heroImageMediaId", "twitterCard", "twitterTitle", "twitterDescription", "twitterSite"],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "security",
    title: "Security",
    description: "Client authentication password",
    icon: "Lock",
    fields: ["password"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "settings",
    title: "Settings",
    description: "Subscription/payment status moved to the Activate/Suspend sidebar pages",
    icon: "Settings",
    // Emptied 2026-06-10: the Settings accordion was removed from the edit form.
    // subscriptionStatus/paymentStatus are now owned by Activate/Suspend only.
    fields: [],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "ymyl",
    title: "YMYL Verification",
    description: "Your Money Your Life — medical/legal/financial credentials for E-E-A-T",
    icon: "Shield",
    fields: ["isYmyl", "ymylCategory", "ymylData"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "cta",
    title: "Primary CTA",
    description: "Primary action on the article, client page, and listing — FORM (booking) or LINK (external)",
    icon: "MousePointerClick",
    fields: ["ctaMode", "ctaLabel", "ctaUrl"],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "additional",
    title: "Additional",
    description: "Classification, organization details, and additional metadata",
    icon: "Plus",
    fields: [
      "newsletterCtaText",
    ],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
] as const;

/**
 * Get all field names from all sections
 */
export function getAllFormFields(): string[] {
  return clientFormSections.flatMap((section) => section.fields);
}

/**
 * Get required fields from all sections
 */
export function getRequiredFields(): string[] {
  return clientFormSections.flatMap((section) => section.required);
}

/**
 * Get sections available in create mode
 */
export function getCreateModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInCreate);
}

/**
 * Get sections available in edit mode
 */
export function getEditModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInEdit);
}

/**
 * Get section by ID
 */
export function getSectionById(id: string): FormSectionConfig | undefined {
  return clientFormSections.find((section) => section.id === id);
}

/**
 * Get visible field count for a section
 * Excludes auto-generated fields and conditionally rendered fields based on mode
 * 
 * @param sectionId - The section ID to count fields for
 * @param isEditMode - Whether the form is in edit mode
 * @returns The number of visible fields that should be counted
 */
export function getVisibleFieldCount(sectionId: string, isEditMode: boolean): number {
  const section = getSectionById(sectionId);
  if (!section) return 0;

  return section.fields.filter((field) => {
    // Exclude auto-generated/auto-calculated fields (show but don't count)
    if (fieldVisibilityRules.autoGenerated.includes(field as any)) {
      return false;
    }

    // For edit-only fields, only count in edit mode
    if (fieldVisibilityRules.editOnly.includes(field as any)) {
      return isEditMode;
    }

    // Count all other fields
    return true;
  }).length;
}
