/**
 * Client Form Configuration
 * Defines all form sections and fields programmatically
 * Updated for tab-based layout
 */

export interface FormSectionConfig {
  id: string;
  title: string;
  description: string;
  icon: string;
  fields: string[];
  required: string[];
  priority: "primary" | "secondary";
  availableInCreate: boolean;
  availableInEdit: boolean;
}

/**
 * Field visibility metadata
 * Defines which fields should be excluded from count or are conditionally rendered
 */
const fieldVisibilityRules = {
  // Auto-generated/auto-calculated fields: show but don't count
  autoGenerated: [] as readonly string[],
  // Edit-only fields: only count in edit mode
  editOnly: ["subscriptionStatus", "paymentStatus"] as readonly string[],
} as const;

export const clientFormSections: FormSectionConfig[] = [
  {
    id: "required",
    title: "Information",
    description: "Key client information needed to create the account",
    icon: "User",
    // Fields: name, slug, email, legalName, foundingDate, industryId, url, phone, contactType, sameAs, slogan, numberOfEmployees, commercialRegistrationNumber, businessBrief, address fields, legal fields
    fields: [
      "name",
      "slug",
      "alternateName",
      "email",
      "legalName",
      "foundingDate",
      "industryId",
      "url",
      "phone",
      "contactType",
      "sameAs",
      "slogan",
      "numberOfEmployees",
      "commercialRegistrationNumber",
      "businessBrief",
      "addressStreet",
      "addressNeighborhood",
      "addressBuildingNumber",
      "addressAdditionalNumber",
      "addressCity",
      "addressRegion",
      "addressPostalCode",
      "addressCountry",
      "addressLatitude",
      "addressLongitude",
      "legalForm",
      "vatID",
      "licenseNumber",
      "licenseAuthority",
      "organizationType",
    ],
    required: ["name", "slug", "email", "businessBrief"],
    priority: "primary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "subscription",
    title: "Subscription",
    description: "Subscription tier, dates, and billing state",
    icon: "CreditCard",
    // Fields: subscriptionTier, subscriptionStartDate, subscriptionEndDate (auto-gen, not counted), subscriptionStatus (edit-only), paymentStatus (edit-only), articlesPerMonth, subscriptionTierConfigId
    fields: [
      "subscriptionTier",
      "subscriptionStartDate",
      "subscriptionEndDate",
      "subscriptionStatus",
      "paymentStatus",
      "articlesPerMonth",
      "subscriptionTierConfigId",
    ],
    required: ["subscriptionTier"],
    priority: "primary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "business",
    title: "Audience",
    description: "Target audience and content priorities",
    icon: "Building2",
    fields: ["targetAudience", "contentPriorities"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "contact",
    title: "Contact",
    description: "Contact information (moved into Information tab)",
    icon: "Mail",
    fields: [],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "address",
    title: "Address",
    description: "Complete address details for local SEO",
    icon: "MapPin",
    fields: [],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "legal",
    title: "Legal",
    description: "Legal information and compliance details (moved into Information tab)",
    icon: "FileText",
    fields: [],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "seo",
    title: "SEO",
    description: "SEO metadata, meta tags, and Google Tag Manager",
    icon: "Search",
    fields: ["seoTitle", "seoDescription", "description", "canonicalUrl", "metaRobots", "gtmId", "organizationType", "keywords", "knowsLanguage", "parentOrganizationId", "businessActivityCode", "isicV4"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "seo-validation",
    title: "SEO & Validation",
    description: "JSON-LD validation and rich results preview",
    icon: "CheckCircle",
    fields: [],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "media-social",
    title: "Media",
    description: "Logo, OG image, Twitter image, and Twitter card settings",
    icon: "Image",
    fields: ["logoMediaId", "ogImageMediaId", "twitterImageMediaId", "twitterCard", "twitterTitle", "twitterDescription", "twitterSite"],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "security",
    title: "Security",
    description: "Client authentication password",
    icon: "Lock",
    fields: ["password"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "settings",
    title: "Settings",
    description: "Client-specific settings and preferences",
    icon: "Settings",
    fields: ["subscriptionStatus", "paymentStatus"],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "additional",
    title: "Additional",
    description: "Classification, organization details, and additional metadata",
    icon: "Plus",
    fields: [
    ],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
] as const;

/**
 * Get all field names from all sections
 */
export function getAllFormFields(): string[] {
  return clientFormSections.flatMap((section) => section.fields);
}

/**
 * Get required fields from all sections
 */
export function getRequiredFields(): string[] {
  return clientFormSections.flatMap((section) => section.required);
}

/**
 * Get sections available in create mode
 */
export function getCreateModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInCreate);
}

/**
 * Get sections available in edit mode
 */
export function getEditModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInEdit);
}

/**
 * Get section by ID
 */
export function getSectionById(id: string): FormSectionConfig | undefined {
  return clientFormSections.find((section) => section.id === id);
}

/**
 * Get visible field count for a section
 * Excludes auto-generated fields and conditionally rendered fields based on mode
 * 
 * @param sectionId - The section ID to count fields for
 * @param isEditMode - Whether the form is in edit mode
 * @returns The number of visible fields that should be counted
 */
export function getVisibleFieldCount(sectionId: string, isEditMode: boolean): number {
  const section = getSectionById(sectionId);
  if (!section) return 0;

  return section.fields.filter((field) => {
    // Exclude auto-generated/auto-calculated fields (show but don't count)
    if (fieldVisibilityRules.autoGenerated.includes(field as any)) {
      return false;
    }

    // For edit-only fields, only count in edit mode
    if (fieldVisibilityRules.editOnly.includes(field as any)) {
      return isEditMode;
    }

    // Count all other fields
    return true;
  }).length;
}
