export const FIELD_LABELS: Record<string, string> = {
  title: "Title",
  slug: "Slug",
  clientId: "Client",
  authorId: "Author",
  categoryId: "Category",
  excerpt: "Excerpt",
  status: "Status",
  featured: "Featured",
  scheduledAt: "Scheduled Date",
  content: "Content",
  contentFormat: "Content Format",
  wordCount: "Word Count",
  readingTimeMinutes: "Reading Time",
  contentDepth: "Content Depth",
  articleBodyText: "Article Body Text (Plain)",
  inLanguage: "Language",
  isAccessibleForFree: "Accessible For Free",
  seoTitle: "SEO Title",
  seoDescription: "SEO Description",
  metaRobots: "Meta Robots",
  canonicalUrl: "Canonical URL",
  sitemapPriority: "Sitemap Priority",
  sitemapChangeFreq: "Sitemap Change Frequency",
  breadcrumbPath: "Breadcrumb Path",
  ogTitle: "Open Graph Title",
  ogDescription: "Open Graph Description",
  ogUrl: "Open Graph URL",
  ogSiteName: "Open Graph Site Name",
  ogLocale: "Open Graph Locale",
  ogType: "Open Graph Type",
  ogArticleAuthor: "OG Article Author",
  ogArticlePublishedTime: "OG Article Published Time",
  ogArticleModifiedTime: "OG Article Modified Time",
  ogArticleSection: "OG Article Section",
  ogArticleTag: "OG Article Tags",
  twitterCard: "Twitter Card Type",
  twitterTitle: "Twitter Title",
  twitterDescription: "Twitter Description",
  twitterSite: "Twitter Site",
  twitterCreator: "Twitter Creator",
  featuredImageId: "Featured Image",
  gallery: "Gallery",
  tags: "Tags",
  faqs: "FAQs",
  datePublished: "Date Published",
  lastReviewed: "Last Reviewed",
  mainEntityOfPage: "Main Entity Of Page",
  license: "License",
  semanticKeywords: "Semantic Keywords",
  citations: "Citations",
  seoKeywords: "SEO Keywords",
  jsonLdStructuredData: "JSON-LD Structured Data",
  jsonLdLastGenerated: "JSON-LD Last Generated",
  jsonLdValidationReport: "JSON-LD Validation Report",
  jsonLdVersion: "JSON-LD Version",
  jsonLdHistory: "JSON-LD History",
  jsonLdDiffSummary: "JSON-LD Diff Summary",
  relatedArticles: "Related Articles",
};
