import type { StepConfig } from "./types";

export const STEP_CONFIGS: StepConfig[] = [
  {
    number: 1,
    label: "Basic",
    id: "basic",
    description: "Essential article information: title, slug, client, and author",
    requiredFields: ["title", "slug", "clientId", "authorId"],
    optionalFields: ["categoryId", "excerpt", "status", "featured", "tags"],
  },
  {
    number: 2,
    label: "Content",
    id: "content",
    description: "Main article content and formatting options",
    requiredFields: ["content"],
    optionalFields: [
      "contentFormat",
      "wordCount",
      "readingTimeMinutes",
      "contentDepth",
      "articleBodyText",
      "inLanguage",
      "isAccessibleForFree",
    ],
  },
  {
    number: 3,
    label: "Media",
    id: "media",
    description: "Images, featured image, and media gallery",
    requiredFields: [],
    optionalFields: ["featuredImageId", "gallery"],
  },
  {
    number: 4,
    label: "FAQs",
    id: "faqs",
    description: "Frequently asked questions",
    requiredFields: [],
    optionalFields: ["faqs"],
  },
  {
    number: 5,
    label: "SEO Keywords",
    id: "keywords",
    description: "Keywords this article is based on (SEO reference).",
    requiredFields: [],
    optionalFields: ["seoKeywords"],
  },
  {
    number: 6,
    label: "Meta Tags",
    id: "meta-tags",
    description: "SEO title, description, and robots meta for search engines.",
    requiredFields: ["seoTitle", "seoDescription"],
    optionalFields: ["metaRobots"],
  },
  {
    number: 7,
    label: "Semantic Keywords",
    id: "semantic-keywords",
    description: "Entities/concepts for disambiguation (e.g. people, places). Optional wikidataId/url.",
    requiredFields: [],
    optionalFields: ["semanticKeywords"],
  },
  {
    number: 8,
    label: "Citations",
    id: "citations",
    description: "External source URLs (E-E-A-T).",
    requiredFields: [],
    optionalFields: ["citations"],
  },
  {
    number: 9,
    label: "Related",
    id: "related",
    description: "Related articles and content connections",
    requiredFields: [],
    optionalFields: ["relatedArticles"],
  },
  {
    number: 10,
    label: "Publication Settings",
    id: "settings",
    description: "Publishing settings, SEO basics, social media, and technical configuration",
    requiredFields: [],
    optionalFields: [
      "scheduledAt",
      "canonicalUrl",
      "twitterSite",
      "twitterCreator",
    ],
  },
  {
    number: 11,
    label: "Technical SEO",
    id: "seo",
    description: "Preview of search results, social sharing, and structured data",
    requiredFields: [],
    optionalFields: ["sitemapPriority", "sitemapChangeFreq", "license"],
  },
  {
    number: 12,
    label: "MetaTag & JSON-LD",
    id: "metatag-preview",
    description: "Metadata object and structured data preview",
    requiredFields: [],
    optionalFields: [],
  },
];
