import type { StepConfig } from "./types";

export const STEP_CONFIGS: StepConfig[] = [
  {
    number: 1,
    label: "Basic",
    id: "basic",
    description: "Title, excerpt, client, category, author, and tags",
    requiredFields: ["title", "slug", "clientId", "authorId"],
    optionalFields: ["categoryId", "excerpt", "status", "featured", "tags"],
  },
  {
    number: 2,
    label: "Content",
    id: "content",
    description: "Article content (rich-text editor + AI assistant)",
    requiredFields: ["content"],
    optionalFields: [
      "contentFormat",
      "wordCount",
      "readingTimeMinutes",
      "contentDepth",
      "articleBodyText",
      "inLanguage",
      "isAccessibleForFree",
    ],
  },
  {
    number: 3,
    label: "Media",
    id: "media",
    description: "Cover image, audio version, and image gallery",
    requiredFields: [],
    optionalFields: ["featuredImageId", "audioUrl", "gallery"],
  },
  {
    number: 4,
    label: "SEO",
    id: "seo",
    description: "SEO title, description, keywords, and semantic keywords",
    requiredFields: ["seoTitle", "seoDescription"],
    optionalFields: ["metaRobots", "seoKeywords", "semanticKeywords"],
  },
  {
    number: 5,
    label: "FAQs",
    id: "faqs",
    description: "Frequently asked questions (FAQ Schema for Google rich results)",
    requiredFields: [],
    optionalFields: ["faqs"],
  },
  {
    number: 6,
    label: "Related",
    id: "related",
    description: "Related articles for internal linking and increased dwell time",
    requiredFields: [],
    optionalFields: ["relatedArticles"],
  },
];
