import type { StepConfig } from "./types";

export const STEP_CONFIGS: StepConfig[] = [
  {
    number: 1,
    label: "Basic",
    id: "basic",
    description: "Title, excerpt, client, category, author, and tags",
    requiredFields: ["title", "slug", "clientId", "authorId"],
    optionalFields: ["categoryId", "excerpt", "status", "featured", "tags"],
  },
  {
    number: 2,
    label: "Content",
    id: "content",
    description: "Article content, featured image, and media gallery",
    requiredFields: ["content"],
    optionalFields: [
      "contentFormat",
      "wordCount",
      "readingTimeMinutes",
      "contentDepth",
      "articleBodyText",
      "inLanguage",
      "isAccessibleForFree",
      "featuredImageId",
      "gallery",
    ],
  },
  {
    number: 3,
    label: "SEO",
    id: "seo",
    description: "SEO title, description, keywords, and semantic keywords",
    requiredFields: ["seoTitle", "seoDescription"],
    optionalFields: ["metaRobots", "seoKeywords", "semanticKeywords"],
  },
  {
    number: 4,
    label: "FAQs & Related",
    id: "faqs-related",
    description: "Frequently asked questions and related articles",
    requiredFields: [],
    optionalFields: ["faqs", "relatedArticles"],
  },
  {
    number: 5,
    label: "Publish",
    id: "publish",
    description: "Publication settings, citations, technical SEO, and metadata preview",
    requiredFields: [],
    optionalFields: [
      "scheduledAt",
      "canonicalUrl",
      "twitterSite",
      "twitterCreator",
      "citations",
      "sitemapPriority",
      "sitemapChangeFreq",
      "license",
    ],
  },
];
