import fs from 'node:fs';
const l = fs.readFileSync('../shared/.env','utf8').split('\n').find(x=>/^\s*DATABASE_URL\s*=/.test(x));
process.env.DATABASE_URL = l.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g,'');
const { PrismaClient } = await import('@prisma/client');
const p = new PrismaClient();
const n = async (k,f)=>{try{console.log(k.padEnd(26), String(await f()).padStart(5))}catch(e){console.log(k.padEnd(26),'ERR')}};
await n('قرّاء مسجّلون (User)', ()=>p.user.count());
await n('مشتركو النشرة', ()=>p.newsSubscriber.count());
await n('تعليقات', ()=>p.comment.count());
await n('إعجابات مقالات', ()=>p.articleLike.count());
await n('مفضّلات', ()=>p.articleFavorite.count());
await n('صفّ مدونتي ككاتب', ()=>p.modonty.count());
await p.$disconnect();
