import { chromium } from '@playwright/test';
const base = 'http://localhost:3001';
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1280, height: 1000 } })).newPage();
const errs = [];
page.on('pageerror', (e) => errs.push(String(e).slice(0, 120)));
page.on('console', (m) => m.type() === 'error' && errs.push(m.text().slice(0, 120)));
await page.goto(`${base}/login`, { waitUntil: 'networkidle' });
await page.fill('input[type="email"]', 'claude-check@modonty.local');
await page.fill('input[type="password"]', 'Mdnty-Local-Check-2026!');
await page.click('button[type="submit"]');
await page.waitForTimeout(5000);
const r = await page.goto(base + '/playbook', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.evaluate(() => document.querySelectorAll('details').forEach(d => (d.open = true)));
await page.waitForTimeout(300);
const t = await page.locator('main').innerText();
const codes = t.match(/\b[A-Z]{3,10}-\d{2}\b/g) || [];
console.log('status', r?.status());
console.log('رموز إنجليزية ظاهرة:', codes.length, codes.slice(0, 8));
console.log('أخطاء كونسول:', errs.length, errs[0] || '');
console.log('الأقسام:', await page.locator('main section[id] h2').evaluateAll(e => e.map(x => x.innerText)));
await browser.close();
