import fs from 'node:fs';
const line = fs.readFileSync('../shared/.env', 'utf8').split('\n').find((l) => /^\s*DATABASE_URL\s*=/.test(l));
process.env.DATABASE_URL = line.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g, '');
const { PrismaClient } = await import('@prisma/client');
const p = new PrismaClient();
const n = async (l, f) => { try { console.log(l.padEnd(38), String(await f()).padStart(5)); } catch (e) { console.log(l.padEnd(38), 'ERR ' + String(e.message).split('\n').filter(Boolean).pop().slice(0,55)); } };
await n('مقالات لها نسخة صوتية (audioUrl)', () => p.article.count({ where: { audioUrl: { not: null } } }));
await n('ريلز (Media بـ reelArticleId)', () => p.media.count({ where: { reelArticleId: { not: null } } }));
await n('شركاء لهم متجر', () => p.client.count({ where: { shopUrl: { not: null } } }));
await n('شركاء يستقبلون حجوزات', () => p.client.count({ where: { acceptsBookings: true } }));
await n('شركاء موثّقون', () => p.client.count({ where: { isVerified: true } }));
await p.$disconnect();
