import fs from 'node:fs';
const line = fs.readFileSync('../shared/.env', 'utf8').split('\n').find((l) => /^\s*DATABASE_URL\s*=/.test(l));
process.env.DATABASE_URL = line.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g, '');
const { PrismaClient } = await import('@prisma/client');
const p = new PrismaClient();
const rows = await p.client.findMany({ select: { ctaMode: true } });
const tally = {};
for (const r of rows) tally[String(r.ctaMode)] = (tally[String(r.ctaMode)] || 0) + 1;
console.log('أبواب الشريك (ctaMode):', tally);
console.log('فيديو تعريفي:', await p.client.count({ where: { OR: [{ introVideoUrl: { not: null } }, { introVideoMediaId: { not: null } }] } }));
console.log('صورة توثيق:', await p.client.count({ where: { verificationImageUrl: { not: null } } }));
console.log('مقالات على موقع الشريك:', await p.article.count({ where: { status: 'PUBLISHED_ON_CLIENT_SITE' } }));
await p.$disconnect();
