import fs from 'node:fs';
const line = fs.readFileSync('../shared/.env', 'utf8').split('\n').find((l) => /^\s*DATABASE_URL\s*=/.test(l));
process.env.DATABASE_URL = line.split('=').slice(1).join('=').trim().replace(/^["']|["']$/g, '');
const { PrismaClient } = await import('@prisma/client');
const p = new PrismaClient();
console.log('أبواب الشريك (ctaMode):', await p.client.groupBy({ by: ['ctaMode'], _count: { _all: true } }));
console.log('\nشركاء لهم فيديو تعريفي:', await p.client.count({ where: { OR: [{ introVideoUrl: { not: null } }, { introVideoMediaId: { not: null } }] } }));
console.log('شركاء لهم صورة توثيق:', await p.client.count({ where: { verificationImageUrl: { not: null } } }));
console.log('مقالات نُشرت على موقع الشريك:', await p.article.count({ where: { status: 'PUBLISHED_ON_CLIENT_SITE' } }));
await p.$disconnect();
