import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });
dotenv.config({ path: "../.env.shared" });
import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();
const email = "ui-ux-temp-tester@modonty.local";
const deleted = await db.staff.delete({ where: { email } }).catch(() => null);
console.log("deleted:", !!deleted);
await db.$disconnect();
