import type { IntakeFieldConfig } from "./intake-questions-types";
import { opt } from "./intake-questions-constants";

export const INTAKE_FIELD_CONFIG: Record<string, IntakeFieldConfig> = {
  q0: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q23: { type: "input" },
  q23b: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q87: { type: "input" },
  q3: { type: "textarea" },
  q5: { type: "select", allowOther: true, options: [opt("b2b", "B2B"), opt("b2c", "B2C"), opt("both", "كلاهما"), opt("saas", "SaaS"), opt("ecommerce", "تجارة إلكترونية"), opt("other", "أخرى")] },
  q7: { type: "select", options: [opt("low", "منخفضة"), opt("medium", "متوسطة"), opt("high", "عالية"), opt("dont_know", "لا أعرف")] },
  q8b: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا"), opt("unsure", "غير متأكد")] },
  q9: { type: "multiselect", options: [opt("traffic", "زيارات"), opt("leads", "عملاء محتملين"), opt("sales", "مبيعات"), opt("brand_awareness", "وعي بالعلامة")] },
  q9b: { type: "textarea" },
  q11: { type: "textarea" },
  q12: { type: "input" },
  q13: { type: "input" },
  q14: { type: "input" },
  q15: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q15_tools: { type: "multiselect", options: [opt("gtm", "GTM"), opt("ga4", "GA4"), opt("hotjar", "Hotjar"), opt("mixpanel", "Mixpanel"), opt("other", "أخرى")] },
  q17b: { type: "textarea" },
  q17c: { type: "textarea" },
  q17d: { type: "textarea" },
  q19: { type: "select", options: [opt("awareness", "الوعي"), opt("consideration", "التفكير"), opt("decision", "القرار"), opt("mix", "مزيج")] },
  q20: { type: "multiselect", options: [opt("ar", "العربية"), opt("en", "الإنجليزية"), opt("other", "أخرى")] },
  q21: { type: "select", options: [opt("mobile", "جوال"), opt("desktop", "سطح المكتب"), opt("50_50", "50/50")] },
  q24: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q25: { type: "select", allowOther: true, options: [opt("wordpress", "WordPress"), opt("nextjs", "Next.js"), opt("shopify", "Shopify"), opt("wix", "Wix"), opt("custom", "مخصص"), opt("dont_know", "غير معروف"), opt("other", "أخرى")] },
  q26: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q27: { type: "select", options: [opt("yes_ok", "نعم بدون مشكلات"), opt("yes_issues", "نعم مع مشكلات"), opt("no_access", "لا وصول"), opt("dont_know", "لا أعرف")] },
  q28: { type: "select", options: [opt("both", "نعم الاثنان"), opt("partial", "جزئياً"), opt("no", "لا"), opt("dont_know", "لا أعرف")] },
  q30: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا"), opt("dont_know", "لا أعرف")] },
  q31: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q34: { type: "textarea" },
  q35: { type: "textarea" },
  q36: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم"), opt("unsure", "غير متأكد")] },
  q37: { type: "textarea" },
  q38: { type: "textarea" },
  q39: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q41: { type: "select", options: [opt("informational", "معلوماتية"), opt("transactional", "معاملاتية"), opt("navigational", "تنقلية"), opt("mix", "مزيج")] },
  q42: { type: "select", options: [opt("long_tail", "طويلة"), opt("head", "رئيسية"), opt("both", "كليهما")] },
  q44: { type: "select", options: [opt("1_10", "1–10"), opt("11_50", "11–50"), opt("51_200", "51–200"), opt("200_plus", "200+")] },
  q45: { type: "select", options: [opt("yes", "نعم"), opt("partial", "جزئياً"), opt("no", "لا")] },
  q46: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q47: { type: "select", options: [opt("readable", "واضحة وقابلة للقراءة"), opt("ids", "معرّفات (IDs)"), opt("mix", "مزيج")] },
  q48: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q50: { type: "select", options: [opt("yes", "نعم"), opt("partial", "جزئياً"), opt("no", "لا")] },
  q51: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q52: { type: "select", options: [opt("no", "لا"), opt("registered", "مسجّل فقط"), opt("optimized", "نعم مسجّل ومحسّن")] },
  q53: { type: "textarea" },
  q54: { type: "select", options: [opt("consistent", "متطابق"), opt("minor", "اختلافات بسيطة"), opt("major", "اختلافات كثيرة")] },
  q55: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q56: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q58: { type: "select", options: [opt("none", "لا متجر"), opt("1_50", "1–50"), opt("51_200", "51–200"), opt("200_plus", "200+")] },
  q59: { type: "select", options: [opt("yes", "نعم"), opt("partial", "جزئياً"), opt("no", "لا")] },
  q63: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q64: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q65: { type: "select", options: [opt("known", "معروف"), opt("medium", "متوسط"), opt("new", "جديد")] },
  q66: { type: "select", options: [opt("some", "نعم قليل"), opt("many", "كثير"), opt("dont_know", "لا أعرف")] },
  q68: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم"), opt("dont_know", "لا أعرف")] },
  q73: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q73_platforms: { type: "multiselect", allowOther: true, options: [opt("facebook", "فيسبوك"), opt("twitter", "تويتر"), opt("linkedin", "لينكدإن"), opt("instagram", "انستغرام"), opt("youtube", "يوتيوب"), opt("tiktok", "تيك توك"), opt("other", "أخرى")] },
  q74: { type: "select", options: [opt("major", "نعم مصدر مهم"), opt("some", "قليل"), opt("rare", "نادراً"), opt("no", "لا")] },
  q77: { type: "textarea" },
  q77b: { type: "textarea" },
  q78: { type: "textarea" },
  q82: { type: "select", options: [opt("low", "منخفض"), opt("medium", "متوسط"), opt("high", "عالٍ")] },
  q85: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا"), opt("partial", "جزئياً")] },
  q88: { type: "select", options: [opt("days", "أيام"), opt("week", "أسبوع"), opt("month", "شهر"), opt("varies", "يعتمد على المشروع")] },
  q89: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q90: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا")] },
  q91: { type: "textarea" },
  q91b: { type: "select", allowOther: true, options: [opt("agency", "وكالة"), opt("freelancer", "فريلانسر"), opt("internal", "داخلي"), opt("none", "لا أحد"), opt("other", "أخرى")] },
  q91c: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا"), opt("limited", "محدود")] },
  q92: { type: "select", options: [opt("no", "لا"), opt("yes", "نعم")] },
  q95: { type: "select", options: [opt("yes", "نعم"), opt("no", "لا"), opt("limited", "محدود")] },
};
