"use server";

import { unstable_cache } from "next/cache";

import { db } from "@/lib/db";
import { ARTICLE_SEO_SELECT, getArticleSeoScoreDetail } from "@/lib/seo/article-seo-score";
import type { SeoCheckTally } from "@/app/(dashboard)/components/seo-health-card";

/**
 * SEO health of EVERY article, regardless of status (Khalid 2026-07-23: an article
 * is an article — draft, published or in revision; the one question is "does it have
 * an SEO problem or not?"). Scored through the ONE shared rubric, from the same stored
 * fields the badge and the segment tables read, so the dashboard number and the list
 * behind it cannot drift.
 *
 * The SAME single pass also tallies WHICH check is blocking 100% and across how many
 * articles — the "why 72" breakdown. Each rubric check is bucketed by who can act on it:
 *   · content — the editor's own levers (SEO title/description, featured image, author)
 *   · system — auto-generated by our code (canonical, hreflang, JSON-LD validity, dates).
 *     A non-zero system count is a BUG alarm, not a content follow-up
 *     (memory: any schema/metadata gap is code's responsibility).
 * Internal-link count is deliberately absent: Google states there is "no magical ideal
 * number of links" — the count gate was removed from the live validator on 2026-05-04.
 *
 * Cached 60s; shares the article-status-counts tag so mutations invalidate it.
 */

const CHECK_META: Record<string, { label: string; bucket: "content" | "system" }> = {
  title: { label: "SEO title", bucket: "content" },
  description: { label: "SEO description", bucket: "content" },
  ogImage: { label: "Share image", bucket: "content" },
  "jsonld.image": { label: "Featured image", bucket: "content" },
  "jsonld.author": { label: "Author", bucket: "content" },
  canonical: { label: "Canonical", bucket: "system" },
  hreflang: { label: "hreflang", bucket: "system" },
  ogArticle: { label: "OG type + date", bucket: "system" },
  "jsonld.valid": { label: "JSON-LD errors", bucket: "system" },
  "jsonld.headline": { label: "JSON-LD headline", bucket: "system" },
  "jsonld.datePublished": { label: "JSON-LD date", bucket: "system" },
  "jsonld.dateModified": { label: "JSON-LD modified", bucket: "system" },
  "jsonld.publisher": { label: "JSON-LD publisher", bucket: "system" },
};

export interface ArticleSeoQuality {
  /** Average SEO score across all articles (sum of scores ÷ count) — the real level. */
  avgScore: number;
  /** Raw sum of every article score — lets the platform overall combine exactly. */
  sumScore: number;
  perfect: number;
  below: number;
  checks: SeoCheckTally[];
}

export const getArticleSeoQuality = unstable_cache(
  async (): Promise<ArticleSeoQuality> => {
    const rows = await db.article.findMany({
      select: ARTICLE_SEO_SELECT,
      take: 1000,
    });
    let perfect = 0;
    let below = 0;
    let sumScore = 0;
    const failing = new Map<string, number>();
    for (const r of rows) {
      const { score, checks } = getArticleSeoScoreDetail(r);
      sumScore += score;
      if (score >= 100) perfect += 1;
      else below += 1;
      // A check that isn't at full marks is what prevents this article from hitting 100.
      for (const c of checks) {
        if (c.earned < c.max) failing.set(c.key, (failing.get(c.key) ?? 0) + 1);
      }
    }
    const avgScore = rows.length > 0 ? Math.round(sumScore / rows.length) : 0;
    const checks: SeoCheckTally[] = [...failing.entries()]
      .map(([key, n]) => {
        const meta = CHECK_META[key];
        return {
          key,
          label: meta?.label ?? key,
          bucket: meta?.bucket ?? "system",
          failing: n,
        } satisfies SeoCheckTally;
      })
      .sort((a, b) => b.failing - a.failing);
    return { avgScore, sumScore, perfect, below, checks };
  },
  ["article-seo-quality"],
  { revalidate: 60, tags: ["article-status-counts"] },
);
