"use server";

import { unstable_cache } from "next/cache";

import { db } from "@/lib/db";
import { computeClientSeoScore } from "@modonty/database/lib/seo/client/seo-score";
import { clientToSeoInput } from "@modonty/database/lib/seo/client/from-client";
import type { SeoCheckTally } from "@/app/(dashboard)/components/seo-health-card";

/**
 * SEO health of EVERY client (Khalid 2026-07-23: same idea as the article side — a
 * client is a client; the one question is "does it have an SEO problem or not?").
 * Scored through the ONE shared client rubric (computeClientSeoScore) via the shared
 * adapter, from the same stored fields the client badge and the SEO clients list read,
 * so the dashboard number and the list behind it cannot drift.
 *
 * The same single pass tallies WHICH check blocks 100%, bucketed by who acts:
 *   · content — the client's own data (their console fills it: logo, hero, description,
 *     contact, address…). We chase the client, not fix it in admin
 *     (memory: client field ownership lives in the console).
 *   · system — auto-generated by our code (canonical, hreflang, JSON-LD graph/validity).
 *     A non-zero system count is a BUG alarm, not a client follow-up.
 *
 * No select: clientToSeoInput reads ~30 raw columns and cannot tell "not selected" from
 * "empty" — findMany returns every scalar, exactly what the shared adapter expects.
 * Cached 60s.
 */

const CHECK_META: Record<string, { label: string; bucket: "content" | "system" }> = {
  title: { label: "SEO title", bucket: "content" },
  description: { label: "SEO description", bucket: "content" },
  ogImage: { label: "Share image", bucket: "content" },
  "jsonld.logo": { label: "Logo", bucket: "content" },
  "jsonld.heroImage": { label: "Hero image", bucket: "content" },
  "jsonld.identity": { label: "Identity", bucket: "content" },
  "jsonld.contact": { label: "Contact", bucket: "content" },
  "jsonld.presence": { label: "Presence", bucket: "content" },
  "jsonld.identifiers": { label: "Business IDs", bucket: "content" },
  "jsonld.local": { label: "Local SEO", bucket: "content" },
  canonical: { label: "Canonical", bucket: "system" },
  hreflang: { label: "hreflang", bucket: "system" },
  "jsonld.graph": { label: "Structured data", bucket: "system" },
  "jsonld.valid": { label: "JSON-LD errors", bucket: "system" },
  "jsonld.warnings": { label: "JSON-LD warnings", bucket: "system" },
};

export interface ClientSeoQuality {
  /** Average SEO score across all clients (sum of scores ÷ count) — the real level. */
  avgScore: number;
  /** Raw sum of every client score — lets the platform overall combine exactly. */
  sumScore: number;
  perfect: number;
  below: number;
  checks: SeoCheckTally[];
}

export const getClientSeoQuality = unstable_cache(
  async (): Promise<ClientSeoQuality> => {
    const rows = await db.client.findMany({ take: 1000 });
    let perfect = 0;
    let below = 0;
    let sumScore = 0;
    const failing = new Map<string, number>();
    for (const r of rows) {
      const { score, checks } = computeClientSeoScore(
        clientToSeoInput(r as unknown as Record<string, unknown>),
      );
      sumScore += score;
      if (score >= 100) perfect += 1;
      else below += 1;
      for (const c of checks) {
        if (c.earned < c.max) failing.set(c.key, (failing.get(c.key) ?? 0) + 1);
      }
    }
    const avgScore = rows.length > 0 ? Math.round(sumScore / rows.length) : 0;
    const checks: SeoCheckTally[] = [...failing.entries()]
      .map(([key, n]) => {
        const meta = CHECK_META[key];
        return {
          key,
          label: meta?.label ?? key,
          bucket: meta?.bucket ?? "system",
          failing: n,
        } satisfies SeoCheckTally;
      })
      .sort((a, b) => b.failing - a.failing);
    return { avgScore, sumScore, perfect, below, checks };
  },
  ["client-seo-quality"],
  { revalidate: 60, tags: ["client-seo-quality"] },
);
