import { Image, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { useState } from 'react';
import { fixtureClient } from '@/src/data/client-fixtures';
import { Card, Screen, SectionTitle, StatusPill } from '@/src/components/ui/MobileUI';
import { ModontyIcon } from '@/src/components/brand/icons/ModontyIcon';
import { fonts } from '@/src/theme/tokens';
import { useAppTheme } from '@/src/theme/ThemeProvider';
import type { MobileClientProfile } from '@/src/services/mobile-api';

export function AccountRoute({ client, onSupport, onLogout }: { client: MobileClientProfile | null; onSupport: () => void; onLogout: () => void }) {
  const { theme } = useAppTheme(); const [criticalAlerts, setCriticalAlerts] = useState(true); const [activityAlerts, setActivityAlerts] = useState(false);
  const displayClient = client ?? fixtureClient;
  const planLabel = `باقة ${client?.subscriptionTier ?? 'Pro'} نشطة`;
  const Row = ({ label, detail, value, onValueChange }: { label: string; detail: string; value: boolean; onValueChange: (next: boolean) => void }) => <View style={[styles.pref, { borderTopColor: theme.colors.border }]}><Switch value={value} onValueChange={onValueChange} trackColor={{ false: theme.colors.border, true: theme.colors.primary }}/><View style={styles.prefCopy}><Text style={[styles.prefLabel, { color: theme.colors.text }]}>{label}</Text><Text style={[styles.prefDetail, { color: theme.colors.muted }]}>{detail}</Text></View></View>;
  return <Screen title="حسابي" icon="profile"><Card style={styles.profile}><View style={[styles.avatar, { backgroundColor: theme.colors.primary }]}>{client?.logoUrl ? <Image source={{ uri: client.logoUrl }} accessibilityLabel={client.logoAlt ?? `شعار ${client.name}`} style={styles.avatarImage} /> : <Text style={styles.initials}>{displayClient.name.slice(0, 2)}</Text>}</View><View style={styles.profileCopy}><Text style={[styles.name, { color: theme.colors.text }]}>{displayClient.name}</Text><Text style={[styles.email, { color: theme.colors.muted }]}>{displayClient.email}</Text><StatusPill>{planLabel}</StatusPill></View></Card><SectionTitle>التنبيهات</SectionTitle><Card><Row label="ما يحتاج إجراء" detail="مقال، سؤال مباشر، أو فشل رفع" value={criticalAlerts} onValueChange={setCriticalAlerts}/><Row label="نشاط المتابعين" detail="تعليقات، متابعات، ومؤشرات" value={activityAlerts} onValueChange={setActivityAlerts}/></Card><SectionTitle>المساعدة</SectionTitle><Pressable onPress={onSupport} accessibilityRole="button" accessibilityLabel="فتح المساعدة والدعم"><Card style={styles.support}><ModontyIcon name="question" size={24} primary={theme.colors.text} accent={theme.colors.primary}/><View style={styles.supportCopy}><Text style={[styles.supportTitle, { color: theme.colors.text }]}>المساعدة والدعم</Text><Text style={[styles.supportDetail, { color: theme.colors.muted }]}>تواصل مع فريق مودونتي من داخل التطبيق</Text></View></Card></Pressable><Pressable onPress={onLogout} accessibilityRole="button" accessibilityLabel="تسجيل الخروج"><Text style={[styles.logout, { color: theme.colors.danger }]}>تسجيل الخروج</Text></Pressable></Screen>;
}

const styles = StyleSheet.create({ profile: { flexDirection: 'row-reverse', gap: 13, alignItems: 'center' }, avatar: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, avatarImage: { width: 54, height: 54, resizeMode: 'contain' }, initials: { color: '#06131A', fontFamily: fonts.medium, fontSize: 18 }, profileCopy: { flex: 1, alignItems: 'flex-end' }, name: { fontFamily: fonts.medium, fontSize: 16, lineHeight: 23, writingDirection: 'rtl' }, email: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, writingDirection: 'ltr', marginTop: 3, marginBottom: 6 }, pref: { minHeight: 72, borderTopWidth: 1, flexDirection: 'row-reverse', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, prefCopy: { flex: 1, alignItems: 'flex-end' }, prefLabel: { fontFamily: fonts.medium, fontSize: 14, lineHeight: 20, writingDirection: 'rtl' }, prefDetail: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, writingDirection: 'rtl', marginTop: 2, textAlign: 'right' }, support: { flexDirection: 'row-reverse', alignItems: 'center', gap: 12 }, supportCopy: { flex: 1, alignItems: 'flex-end' }, supportTitle: { fontFamily: fonts.medium, fontSize: 14, writingDirection: 'rtl' }, supportDetail: { fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, writingDirection: 'rtl', marginTop: 3 }, logout: { fontFamily: fonts.medium, fontSize: 14, textAlign: 'center', writingDirection: 'rtl', paddingVertical: 25 } });
